### ISSUE TITLE
Support for Geospatial Queries

### ISSUE THREAD

**Issue by benjaminjs** [mapd/mapd-core#1]
Would be super useful for a lot of different types of spatial analysis.

**Comment by billmaimone** [comment]
Definitely, we can collaborate on this.

**Comment by asuhan** [comment]
Note that there's a `distance_in_meters` function you can call to find the distance between two WGS-84 positions: https://github.com/mapd/mapd-core/blob/master/QueryEngine/ExtensionFunctions.hpp#L227.

**Comment by benjaminjs** [comment]
Yeah, I've dug through the docs on the website. Looking for stuff like ST_Contains for polygons and points.

But the link to the source code is quite handy for seeing how these functions are implemented.

**Comment by m1mc** [comment]
`contains` should be easy by adding another function to compute barycentric coordinates w/ it for triangles and dot product for others etc.

**Comment by dfernan** [comment]
I'd merge this issue with this one: https://github.com/mapd/mapd-core/issues/58

**Comment by mflaxman10** [comment]
This should probably be closed with the 4.0 release, which now supports geo features, and ST_DISTANCE and ST_CONTAINS geoprocessing ops mentioned above.  @m1mc, @billmaimone  and @benjaminjs: are you finding what you need now?  If not, perhaps open a new issue - MapD is looking for community contributions/priorities for its geo road map.  ST_INTERSECTION, ST_AREA, etc. could make  fun projects for interested geogeeks!

**Comment by benjaminjs** [comment]
Yep, exactly what I was looking for!
