### ISSUE TITLE
QT Error when building thrift dependency

### ISSUE THREAD

**Issue by mccarthyryanc** [mapd/mapd-core#101]
Building for Ubuntu 16.04, I got the same error mentioned [here](https://issues.apache.org/jira/browse/THRIFT-1828?jql=text%20~%20%22moc__TQTcpServer%22):

```
src/thrift/qt/moc_TQTcpServer.cpp:14:2: error: #error "This file was generated using the moc from 4.8.1. It"
src/thrift/qt/moc_TQTcpServer.cpp:15:2: error: #error "cannot be used with the include files from this version of Qt."
src/thrift/qt/moc_TQTcpServer.cpp:16:2: error: #error "(The moc has changed too much.)"
```

 Looks like there was a conflict between different versions of QT. I was able to get a work around by adding `--with-qt5=no` to the thrift build step in `mapd-deps-ubuntu.sh`:

```diff
diff --git a/scripts/mapd-deps-ubuntu.sh b/scripts/mapd-deps-ubuntu.sh
index 5393db7..1cb4052 100755
--- a/scripts/mapd-deps-ubuntu.sh
+++ b/scripts/mapd-deps-ubuntu.sh
@@ -70,6 +70,7 @@ JAVA_PREFIX=$PREFIX/lib ./configure \
     --with-python=no \
     --with-php=no \
     --with-ruby=no \
+    --with-qt5=no \
     --prefix=$PREFIX
 make -j $(nproc)
 make install
```

**Comment by randyzwitch** [comment]
Closing this issue. If this is still a problem with one of our current 4.x releases, please open a new issue or start a conversation at https://community.mapd.com/
