### ISSUE TITLE
Multi-table join error: "Check failed: it != plan_state_->global_to_local_col_ids_.end()"

### ISSUE THREAD

**Issue by miiklay** [mapd/mapd-core#108]
Customer is getting:
`F1010 22:22:06.439077 51520 Execute.cpp:2513] Check failed: it != plan_state_->global_to_local_col_ids_.end()`

From this query:
`select cons.cons_no, obj.coll_obj_id, obj.meter_id, fdmeter.asset_no, cons.contract_cap, case when cmeter.t_factor is Null then 1 when cmeter.t_factor = 0 then 1 else cmeter.t_factor end t_factor, case when floor(fdmeter.meter_digits) in (4,5,6) then floor(fdmeter.meter_digits) else 5 end as meter_digits, fdmeter.wiring_mode, fdmeter.volt_code, fdmeter.rated_current,mp.mp_id from d_meter1 fdmeter, r_coll_obj1 obj, c_meter1 cmeter, c_meter_mp_rela1 rela, c_mp1 mp, c_cons1 cons, r_tmnl_run1 run where fdmeter.meter_id = obj.meter_id and obj.meter_id = cmeter.meter_id and cmeter.meter_id = rela.meter_id and obj.cp_no = run.cp_no and mp.mp_id = rela.mp_id and cons.cons_id = mp.cons_id and mp.status_code = '02' and run.status_code in ( '01', '04', '06', '02', '07') and run.terminal_type_code in ('05','06') and obj.coll_obj_type = 0 and obj.delete_flag = 0 limit 1;`

DDL and data have been provided and are at:
`/theHoard/export/internal-data/geiri`

Tables set up and loaded (and issue can be reproduced) at:
`/raidStorage/prod/mapd/bin/mapdql -u mikeg -p mikeg mikegdb
`

**Comment by asuhan** [comment]
I'll have a look this week, I think we'll have it working very soon.

**Comment by asuhan** [comment]
Fixed by d4b060ae2eed5dafa1cce80020f645b379b7b625, we'll have it in the upcoming release.
