### ISSUE TITLE
Does Folly needed by mapd?

### ISSUE THREAD

**Issue by neko940709** [mapd/mapd-core#11]
I follow the installation guide of the mapd, and I found error like this:
`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Folly (missing: Folly_LIBRARY Folly_DC_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFolly.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:95 (find_package)
`
Does Folly needed by mapd?And what version of Folly should install?

**Comment by asuhan** [comment]
Currently, you can build without Folly with `-DENABLE_FOLLY=OFF`, but this isn't recommended and might change anyway. The readme recommends 2017.04.10.00, per the https://github.com/mapd/mapd-core#ubuntu-1604-1610 section. It's available at https://github.com/facebook/folly/archive/v2017.04.10.00.tar.gz.

**Comment by neko940709** [comment]
Thanks for your answer,and now I have finished the installation of dependencies. I found your dependencies script was not really commonly used towards various environment, and I hope it will be improved.

**Comment by randyzwitch** [comment]
Closing this issue for now, but please feel free to open another issue if this is still a problem.
