### ISSUE TITLE
Update GetServerInfo to include # of GPUs, GPU memory and CPU memory

### ISSUE THREAD

**Issue by mythilimapd** [mapd/mapd-core#118]
Logging this request for Todd

We want some static information on the # of GPUs,  CPU memory and GPU memory as part of the GetServerInfo()

**Comment by dwayneberry** [comment]
All this information is available via get_memory call.  I assume this is a one time request from immerse so making a call to that api should be quick and low overhead

**Comment by billmaimone** [comment]
https://github.com/mapd/mapd-core/commit/08156f45fe247419184a6d1cfb765ea542b96878
