### ISSUE TITLE
Include \o mapdql command in the \h listing

### ISSUE THREAD

**Issue by DennisDawson** [mapd/mapd-core#119]
The `\o <table_name>` command does not currently appear in the `\h` listing from mapdql. (If there are other useful switches missing from the `\h` output, please include those, as well.)

**Comment by ptumati** [comment]
Can be closed; added in c606e9f2fa4833ff267b2ff7095208fe46e8ecd6 with a minor update in 9827494f5612d78f15d7730fa1a67dd0504945b9.

**Comment by randyzwitch** [comment]
@DennisDawson Can you close this issue? It appears to have been fixed

**Comment by DennisDawson** [comment]
Closing this specific issue, but there remains the broader issue of whether all of the commands we want to expose to the public are in the \h text, and none that we do not.
