### ISSUE TITLE
Cuda driver moved in homebrew

### ISSUE THREAD

**Issue by hung135** [mapd/mapd-core#12]
Looks like the Cuda driver moved for OSX.
Error: No available formula with the name "cuda" 
It was migrated from caskroom/cask to caskroom/drivers.
You can access it again by running:
  brew tap caskroom/drivers

brew cask install cuda works after the above statement was ran.

**Comment by asuhan** [comment]
@andrewseidl Should we update the documentation?

**Comment by hung135** [comment]
need to update this file also.
https://github.com/mapd/mapd-core/blob/master/scripts/mapd-deps-osx.sh

**Comment by andrewseidl** [comment]
Done. Thanks for letting us know - it looks like Caskroom moved things around on us a couple weeks ago.
