### ISSUE TITLE
Exception: connect() fails after a query that needs more than available memory failed for several times

### ISSUE THREAD

**Issue by fleapapa** [mapd/mapd-core#121]
[UPDATE]
To reproduce: Submit a query on a table that needs more than available memory (so it will fail). The table spans 509 files.

Symptom: After the query fails, further query will return "Exception: connect() failed: Connection refused".

At this time, /proc/`pidof mapd_server`/status shows FDSize max out like below:

$ ps ax|grep mapd_server
19452 pts/9    S+     0:20 gdb bin/mapd_server
25066 pts/9    tl     0:52 /mnt/mapd-core/bin/mapd_server --data /mnt/trip/mapd/data

$ less /proc/25066/status
Name:   mapd_server
Umask:  0002
State:  t (tracing stop)
Tgid:   25066
Ngid:   0
Pid:    25066
PPid:   19452
TracerPid:      19452
Uid:    1001    1001    1001    1001
Gid:    1001    1001    1001    1001
FDSize: 1024

Though enlarged ulimit can alleviate the issue, it does not uproot the cause.

**Comment by fleapapa** [comment]
As further investigated, 1024 fds were allocated but only 538 fds were in use, so the root cause is not out of file descriptors, though the reason of connection failure is on proto::connect(). 

Trying to reproduce it...

**Comment by fleapapa** [comment]
It turns out to be a "defunct" Calcite server that caused further queries to get "Exception: connect() failed: Connection refused" error after two or three failed queries that need too much memory.

```
$ ps ax|grep java
23697 pts/9    Z+     0:03 [java] <defunct>
```
Wondering if Calcite was gone also from OOM.

**Comment by dwayneberry** [comment]
Possibly the Linux out of memory killer may be the culprit, on a tight memory system like yours, take a look in the system logs.

**Comment by fleapapa** [comment]
@dwayneberry, thanks. There is no sign of OOM in syslog in last few hours. Besides, my VM has 8GB swap space; it showed no sign of being used. Unlikely Calcite would use as much as mapd_server during that period.

**Comment by fleapapa** [comment]
BTW, in my thought, the scenario of running a query of 47GB table on my 14GB VM should be analogous to that of running a query of 4TB table on a system with 1TB memory.

**Comment by fleapapa** [comment]
@dwayneberry. While i tracing the execution of a big query, after the first batch of (ExecutionDispatch) threads were joined, i saw something suspicious in cpu buffer list, so i added this code in function BufferMgr::findFreeBuffer (line #333):

```
LOG(INFO) << "\t\t" << evictIt->startPage << "/" << evictIt->numPages << ":"
<< (evictIt->memStatus == USED? "used, ": "free, ") << evictIt->pinCount << ", " << showChunk(evictIt->chunkKey);

```

For example, the buffer "2050783/585938:used, 0, 1,1,1,1," showed up 3 times. 

Is this duplication ok?

```
I1019 09:20:58.977927 14345 BufferMgr.cpp:333] 		0/585938:used, 0, 1,1,1,0,
I1019 09:20:58.978253 14345 BufferMgr.cpp:333] 		585938/585938:used, 0, 1,1,2,0,
I1019 09:20:58.978281 14345 BufferMgr.cpp:333] 		1171876/585938:used, 0, 1,1,9,1,
I1019 09:20:58.978299 14345 BufferMgr.cpp:333] 		1757814/585938:used, 0, 1,1,1,3,
I1019 09:20:58.978315 14345 BufferMgr.cpp:333] 		2343752/585938:used, 0, 1,1,2,3,
I1019 09:20:58.978332 14345 BufferMgr.cpp:333] 		2929690/585938:used, 0, 1,1,3,3,
I1019 09:20:58.978348 14345 BufferMgr.cpp:333] 		3515628/491458:used, 0, 1,1,1,6,
I1019 09:20:58.978364 14345 BufferMgr.cpp:333] 		4007086/491458:used, 0, 1,1,2,6,
I1019 09:20:58.978380 14345 BufferMgr.cpp:333] 		4498544/491458:used, 0, 1,1,3,6,
I1019 09:20:58.978396 14345 BufferMgr.cpp:333] 		4990002/245729:used, 0, 1,1,4,6,
I1019 09:20:58.978412 14345 BufferMgr.cpp:333] 		5235731/491458:used, 0, 1,1,5,6,
I1019 09:20:58.978428 14345 BufferMgr.cpp:333] 		5727189/982916:used, 0, 1,1,6,6,
I1019 09:20:58.978477 14345 BufferMgr.cpp:333] 		6710105/292969:used, 0, 1,1,4,3,
I1019 09:20:58.978497 14345 BufferMgr.cpp:333] 		7003074/585938:used, 0, 1,1,5,3,
I1019 09:20:58.978513 14345 BufferMgr.cpp:333] 		7589012/585938:used, 0, 1,1,3,0,
I1019 09:20:58.978528 14345 BufferMgr.cpp:333] 		8174950/213658:free, 0, 
I1019 09:20:58.978545 14345 BufferMgr.cpp:333] 		0/585938:used, 0, 1,1,5,0,
I1019 09:20:58.978561 14345 BufferMgr.cpp:333] 		585938/585938:used, 0, 1,1,1,5,
I1019 09:20:58.978577 14345 BufferMgr.cpp:333] 		1171876/292969:used, 0, 1,1,4,2,
I1019 09:20:58.978595 14345 BufferMgr.cpp:333] 		1464845/585938:used, 0, 1,1,5,2,
I1019 09:20:58.978610 14345 BufferMgr.cpp:333] 		2050783/585938:used, 0, 1,1,1,1,
I1019 09:20:58.978626 14345 BufferMgr.cpp:333] 		1464845/585938:used, 0, 1,1,5,2,
I1019 09:20:58.978642 14345 BufferMgr.cpp:333] 		2050783/585938:used, 0, 1,1,1,1,
I1019 09:20:58.978658 14345 BufferMgr.cpp:333] 		2050783/585938:used, 0, 1,1,1,1,
I1019 09:20:58.978674 14345 BufferMgr.cpp:333] 		2636721/585938:used, 0, 1,1,2,1,
I1019 09:20:58.978690 14345 BufferMgr.cpp:333] 		3222659/292969:used, 0, 1,1,4,0,
I1019 09:20:58.978739 14345 BufferMgr.cpp:333] 		3515628/585938:used, 0, 1,1,1,4,
I1019 09:20:58.978757 14345 BufferMgr.cpp:333] 		4101566/585938:used, 0, 1,1,2,4,
I1019 09:20:58.978775 14345 BufferMgr.cpp:333] 		4687504/982916:used, 0, 1,1,7,6,
I1019 09:20:58.978790 14345 BufferMgr.cpp:333] 		5670420/245729:used, 0, 1,1,8,6,
I1019 09:20:58.978806 14345 BufferMgr.cpp:333] 		5916149/491458:used, 0, 1,1,9,6,
I1019 09:20:58.978823 14345 BufferMgr.cpp:333] 		6407607/585938:used, 0, 1,1,3,1,
I1019 09:20:58.978839 14345 BufferMgr.cpp:333] 		6993545/292969:used, 0, 1,1,4,1,
I1019 09:20:58.978855 14345 BufferMgr.cpp:333] 		7286514/585938:used, 0, 1,1,5,1,
I1019 09:20:58.978871 14345 BufferMgr.cpp:333] 		7872452/292969:used, 0, 1,1,8,3,
I1019 09:20:58.978886 14345 BufferMgr.cpp:333] 		8165421/223187:free, 0, 
I1019 09:20:58.978902 14345 BufferMgr.cpp:333] 		0/1171875:used, 0, 1,1,6,1,
I1019 09:20:58.978919 14345 BufferMgr.cpp:333] 		1171875/1171875:used, 0, 1,1,7,1,
I1019 09:20:58.978935 14345 BufferMgr.cpp:333] 		2343750/1171875:used, 0, 1,1,6,3,
I1019 09:20:58.978951 14345 BufferMgr.cpp:333] 		3515625/1171875:used, 0, 1,1,7,3,
I1019 09:20:58.978967 14345 BufferMgr.cpp:333] 		4687500/585938:used, 0, 1,1,9,3,
I1019 09:20:58.978983 14345 BufferMgr.cpp:333] 		5273438/585938:used, 0, 1,1,3,4,
I1019 09:20:58.978999 14345 BufferMgr.cpp:333] 		5859376/292969:used, 0, 1,1,8,1,
I1019 09:20:58.979013 14345 BufferMgr.cpp:333] 		6152345/481056:free, 0, 
E1019 09:20:58.979028 14345 BufferMgr.cpp:372] ALLOCATION failed to find 600000000B throwing out of memory CPU_MGR:0

```

**Comment by fleapapa** [comment]
@dwayneberry. Sorry. The duplication is a false alarm. i insert the logging statement at wrong place, resulting in the duplication.

**Comment by RedAlice64** [comment]
Can you post the system you are using? I am trying to reproduce the situation. With CentOS, 7.5GB memory and a 55 GB CSV file the system simply freezes and the CPU Usage fall back after a while without  the client responding to IO.

**Comment by fleapapa** [comment]
Sorry. The version of 'system' i was using when i saw this issue has been heavily changed. Will get back to reproduce this issue later. However, running mapd_server in gdb, i frequently ran into the issue after one or more "heavy" failed or cancelled queries. When that happened, mapd_server was still alive but calcite server had gone.

**Comment by dwayneberry** [comment]
closing as not reproducible
