### ISSUE TITLE
Compiler error with folly : gflags invalid

### ISSUE THREAD

**Issue by xuxilei** [mapd/mapd-core#13]
my OS is CENTOS 7
I download folly-2017.04.10.00.zip , but some wrong with folly 
[root@localhost folly]# ./configure --prefix=/usr/local/mapd-deps
then "checking for main in -lgflags... yes

checking for gflags viability... no

configure: error: "gflags invalid, see config.log for details"

I am make gflags as compiler: /usr/local/lib/libgflags.a , is a static lib
vi config.log , said:

/usr/local/lib/libgflags.a(gflags.cc.o): In function `google::(anonymous namespace)::FlagRegistry::GlobalRegistry()':

gflags.cc:(.text+0xe96): undefined reference to `pthread_rwlock_wrlock'

gflags.cc:(.text+0xeae): undefined reference to `pthread_rwlock_unlock'

gflags.cc:(.text+0xf47): undefined reference to `pthread_rwlock_init'

**Comment by asuhan** [comment]
We haven't tried to build on CentOS 7 as far as I know, looks like Folly doesn't build on that platform. You can build MapD without Folly, by passing `-DENABLE_FOLLY=OFF` to cmake or try to fix the Folly build on CentOS 7 on your own. It looks like a missing or misplaced `-pthread`.

**Comment by dwayneberry** [comment]
Please follow these instructions here for centos 7

https://github.com/mapd/mapd-core#centos-7

We have a set of prebuild dependencies which should work for you and save you building them yourself.

**Comment by randyzwitch** [comment]
Closing, as instructions given for building Centos7 show how to make this work
