### ISSUE TITLE
segmentation fault executing copygeo

### ISSUE THREAD

**Issue by alexei-grigoriev** [mapd/mapd-core#135]
Getting a segfault when providing less then two arguments

> $MAPD_PATH/bin/mapdql -u mapd -p HyperInteractive 
> User mapd connected to database mapd
> mapdql> \copygeo
> Segmentation fault

Same issue when I provide only one argument.
uname -a
Linux alexgg-laptop 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$MAPD_PATH/bin/mapdql -v
MapDQL Version: 3.3.1-20171108-32e7bcc

from syslog:
Dec  1 23:11:13 alexgg-laptop mapd_server[2716]: E1201 23:11:13.780602  8966 MapDHandler.cpp:3260] Exception: Parse failed: Encountered "<EOF>" at line 0, column 0.

Dec  1 23:11:37 alexgg-laptop kernel: [29434.798282] show_signal_msg: 5 callbacks suppressed
Dec  1 23:11:37 alexgg-laptop kernel: [29434.798288] mapdql[8965]: segfault at 0 ip 00007f3fcf98a746 sp 00007ffc76648788 error 4 in libc-2.23.so[7f3fcf8ff000+1c0000]
Dec  1 23:12:55 alexgg-laptop kernel: [29513.381928] mapdql[9025]: segfault at 0 ip 00007f4adbe5c746 sp 00007ffcb23ef3d8 error 4 in libc-2.23.so[7f4adbdd1000+1c0000]

**Comment by ptumati** [comment]
Confirmed.

This one is a faulty strtok() going off the end when there are no added parameters.  I can take care of this one also, unless there are any objections.

**Comment by ptumati** [comment]
I corrected this issue in the Issue135Fix branch ptumati/mapd-core (see: f42e5ea7fca12d3f0e509a6bb00483b535ddb4b5 ).  

The unsafe strtok() behavior is replicated in other places, however.  For example, with \ste, if a parameter is not specified, random garbage in memory is used to construct a string which is then processed and fed into a thrift request.  

A more general solution with adequate testing is still preferable.  If my fix is useful, however, a pull from my Issue135Fix branch can help.
