### ISSUE TITLE
FLOOR() is an aggregate function?

### ISSUE THREAD

**Issue by pramsey** [mapd/mapd-core#136]
Running this query:
```
select 
 avg(tip_amount) as tip_amount,
 avg(fare_amount) as fare_amount,
 avg(pickup_merc_x) as pickup_merc_x,
 avg(pickup_merc_y) as pickup_merc_y 
from taxi_weather_tracts_factual
group by
  floor(pickup_merc_x)
```
I get this response
```
Exception: Exception occurred: org.apache.calcite.runtime.CalciteContextException: From line 1, column 80 to line 1, column 99: Aggregate expression is illegal in GROUP BY clause
```
Which seems odd to me, as I expected FLOOR() to be an ordinary math function, not an aggregate.
```
The Server Version Number  : 3.3.1-20171108-32e7bcc
The Server Start Time      : 2017-12-04 : 17:4:19
The Server edition         : 3.3.1-20171108-32e7bcc
```

**Comment by dwayneberry** [comment]
Your sql is re-aliases the column name `pickup_merc_x` and as we allow alias on `group by` so it translates into something broken like

```
group by floor ( avg(pickup_merc_x) )
```
Don't re-alias to the same as the real column name you want to do the `floor` on, and you should be good.

That is a very specific data set, may I ask where you got it from?

**Comment by pramsey** [comment]
Thanks! The data set came packaged w/ the rpm I installed following your install directions.

**Comment by dwayneberry** [comment]
Oh this is aws instance?

**Comment by pramsey** [comment]
Yes.
