### ISSUE TITLE
add search filters to various mapdql commands

### ISSUE THREAD

**Issue by billmaimone** [mapd/mapd-core#138]
mapdql commands such as \t \v \u may return quite a long list. These would be more convenient with an optional regex match pattern to filter the result.

**Comment by ptumati** [comment]
I'll claim this one if there's no one else on this.  Is using the <regex> header and associated constructs (with an ECMAScript grammar) for the regexes acceptable?

**Comment by shtilman** [comment]
Sure, it's yours.
We use boost quite extensively, take a look at boost::regex.
The header file to include: <boost/regex.hpp>
