### ISSUE TITLE
compiler of thrift-0.10.0 error: libboost_unit_test_framework.a: No such file or directory

### ISSUE THREAD

**Issue by xuxilei** [mapd/mapd-core#14]
make -j $(nproc)
.........
g++: error: /usr/lib64/libboost_unit_test_framework.a: No such file or directory

**Comment by asuhan** [comment]
Looks like you don't have the Boost Test library installed. I'm not familiar with CentOS, but I believe you should install the `boost-test` package first. Alternatively, it might work if you do `make install` and ignore this problem -- the Thrift compiler and the runtime should be done by the time you hit this problem.

Also, this is more of a Thrift problem, you could try reporting it to the Apache Thrift people if my suggestion to install `boost-test` doesn't fix it.

**Comment by dwayneberry** [comment]
I am assuming you are still working on Centos 7

Please follow these instructions here for centos 7

https://github.com/mapd/mapd-core#centos-7

We have a set of prebuild dependencies which should work for you and save you building them yourself.
