### ISSUE TITLE
startmapd does not seem to be able use mapd.conf

### ISSUE THREAD

**Issue by rvlander** [mapd/mapd-core#148]
A config option is passed to startmapd script in the Dockerfile
```
CMD /mapd/startmapd --non-interactive --data /mapd-storage/data --config /mapd-storage/mapd.conf
```
But startmapd script does not handle this option.

What is the way to configure MapD when using Docker?

Thanks.

**Comment by andrewseidl** [comment]
The config file will be used if it's available at `/mapd-storage/mapd.conf` inside the container.

For example, if I start the container using:

```
nvidia-docker run \
  -d \
  --rm \
  --name mapd \
  -p 9091-9092:9091-9092 \
  -v /home/username/mapd-storage:/mapd-storage \
  -v /usr/share/glvnd/egl_vendor.d:/usr/share/glvnd/egl_vendor.d:ro \
  mapd/mapd-ce-cuda:v3.3.1
```

then I'd want to place the config file at `/home/username/mapd-storage/mapd.conf` on the host.

Note: `startmapd` currently overrides a few config options such as `port` and `data`, so those settings in the config file will be ignored.

**Comment by rvlander** [comment]
The issue is that `startmapd` script does not use the `--config` option that is passed in the Dockerfile.

> Note: startmapd currently overrides a few config options such as port and data, so those settings in the config file will be ignored.

OK. It is clearer why the port did not change when changing the `mapd.conf` file.

**Comment by rvlander** [comment]
The initial goal was to disable auto-login, using `mapd.conf` file and `servers.json` but the docker instance remains blind to whatever changes done in these.

**Comment by andrewseidl** [comment]
Ok, that clarifies things. You're right, the `--config` option isn't being pushed down to the web server. I just pushed a fix, though it will be a couple weeks until it gets picked up into the next release.

In the meantime you can fix your specific issue by mounting your `servers.json` at `/mapd/frontend/servers.json` inside the container:

```
nvidia-docker run \
  ... 
  - v /home/username/mapd-storage/servers.json:/mapd/frontend/servers.json \
  mapd/mapd-ce-cuda
```
