### ISSUE TITLE
Build uses wrong version of LLVM

### ISSUE THREAD

**Issue by domoritz** [mapd/mapd-core#15]
I tried to compile mapd on my ubuntu 16.04 machine but it kept using the old llvm 3.6.0 version. Eventually, I changed `set(llvm_config_cmd llvm-config)` in https://github.com/mapd/mapd-core/blob/5a5dcc2aa94c7c507de58ca2cd201530964666cd/CMakeLists.txt#L156 to `set(llvm_config_cmd llvm-config-3.9)` and the build succeeded. 

I'm not sure whether there is anything you can do but I wanted to note down the steps I took to make it work.

**Comment by m1mc** [comment]
Hi @domoritz, could you run `llvm-config --version` and `clang++ --version` on your machine?
Maybe you should alias default LLVM toolchain to installed 3.9+.

**Comment by domoritz** [comment]
They show version 3.6. Yes, the problem is that the default LLVM versions. I just wanted to note down this fix for others who are running into similar issues because of LLVM 3.6. For example, the build failed with `error: ‘Metadata’ is not a member of ‘llvm’` for me. 

I'm going to close this issue as it is not a problem with MapD but maybe this helps someone else in the future.
