### ISSUE TITLE
auto-complete `SELECT` keyword | get_completion_hints 

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-core#150]
- [ ] auto-complete `SELECT` keyword

  **test case** `"sel col from tablename" 3`
  **complete call** `./MapD-remote -h bewdy.mapd.com:39091 get_completion_hints "session_id"  "sel col from tablename" 3`
  **response** `[]` 
  **expected response** `[TCompletionHint(type=7, hints=['SELECT'], replaced='sel')]`

**Comment by asuhan** [comment]
Fixed by c9eb1331f6e97fd454af6c8f0e8784aeffc8c687.

**Comment by micahstubbs** [comment]
tested, this works as well 🎉 

`[TCompletionHint(type=7, hints=['SELECT'], replaced='sel')]`
