### ISSUE TITLE
provide hints for substrings that are at the end of the queryString | get_completion_hints

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-core#151]
- [ ] provide hints for substrings that are at the end of the queryString

  **test case** `"select * fr" -1`
  **complete call** `./MapD-remote -h bewdy.mapd.com:39091 get_completion_hints "session_id"  "select * fr" -1`
  **response** `[]`
  **expected response** `[TCompletionHint(type=7, hints=['FROM'], replaced='fr')]`

**Comment by asuhan** [comment]
Fixed by c9eb1331f6e97fd454af6c8f0e8784aeffc8c687.

**Comment by micahstubbs** [comment]
tested, this works 🎉 

`[TCompletionHint(type=7, hints=['FROM'], replaced='fr')]`
