### ISSUE TITLE
provide hints for table names | get_completion_hints

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-core#152]
- [ ] provide hints for table names.  in this example, I have a table named `iris` that I would like to complete from the substring `ir` at cursorPosition `18` 

  **test case** `"select col from ir limit 10" 18`
  **complete call** `./MapD-remote -h bewdy.mapd.com:39091 get_completion_hints "session_id"  ""select col from ir limit 10" 18`
   **response** `[]`
  **expected response** `[TCompletionHint(type=7, hints=['iris'], replaced='ir')]`

**Comment by asuhan** [comment]
https://github.com/mapd/mapd-core/pull/142/commits/9b23f258ae984eec07e9ad2752a046c7aca47ea8 fixes this.

**Comment by micahstubbs** [comment]
can verify that this works.  nice! 🎉 

`[TCompletionHint(type=1, hints=['iris'], replaced='ir')]`

![screen shot 2018-01-08 at 2 30 38 pm](https://user-images.githubusercontent.com/2119400/34695679-8aee69a0-f480-11e7-8818-2e6fa544f1b3.png)
