### ISSUE TITLE
Query failed : Exception: Cast from BOOLEAN to BOOLEAN not supported

### ISSUE THREAD

**Issue by mainstreet439** [mapd/mapd-core#157]
per original description at https://community.mapd.com/t/query-failed-exception-cast-from-boolean-to-boolean-not-supported/900

While MAPD doesn’t claim to support distinct predicate, this results in an expected error, suggesting re-written query failing.

select rnum, tsint.csint from tsint where tsint.csint is distinct from 1
Error: Query failed : Exception: Cast from BOOLEAN to BOOLEAN not supported

create table if not exists TSINT ( RNUM integer not null , CSINT smallint );
insert into TSINT(RNUM, CSINT) values ( 0, NULL);
insert into TSINT(RNUM, CSINT) values ( 1, -1);
insert into TSINT(RNUM, CSINT) values ( 2, 0);
insert into TSINT(RNUM, CSINT) values ( 3, 1);
insert into TSINT(RNUM, CSINT) values ( 4, 10);

**Comment by randyzwitch** [comment]
Closing in lieu of #173
