### ISSUE TITLE
in centos 7, bash deploy.sh is wrong

### ISSUE THREAD

**Issue by xuxilei** [mapd/mapd-core#16]
it is wrong.

[root@localhost ~]# curl -OJ https://internal-dependencies.mapd.com/mapd-deps/deploy.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100  1768  100  1768    0     0   1050      0  0:00:01  0:00:01 --:--:--  1049

[root@localhost ~]# sudo bash deploy.sh

........................................

+ FLAG=latest

+ '[' '' == --testing ']'

+ sudo wget --continue https://internal-dependencies.mapd.com/mapd-deps/mapd-deps-latest.tar.xz

--2017-05-22 21:47:56--  https://internal-dependencies.mapd.com/mapd-deps/mapd-deps-latest.tar.xz

Resolving internal-dependencies.mapd.com (internal-dependencies.mapd.com)... failed: Name or service not known.

wget: unable to resolve host address ?.nternal-dependencies.mapd.com?

**Comment by andrewseidl** [comment]
Try running it again, there might just be some intermittent issues with your upstream nameserver. You clearly can resolve it since that's the domain the deploy script was downloaded from, but it might be that the second lookup isn't cached locally and your upstream nameserver fails to resolve again.

If it's still an issue, try adding the following line to your `/etc/hosts` file:

    72.28.97.165 internal-dependencies.mapd.com

**Comment by xuxilei** [comment]
after edit "72.28.97.165 internal-dependencies.mapd.com"
[root@localhost ~]# sudo bash deploy.sh
...................................
+ FLAG=latest

+ '[' '' == --testing ']'

+ sudo wget --continue https://internal-dependencies.mapd.com/mapd-deps/mapd-deps-latest.tar.xz

--2017-05-23 03:17:12--  https://internal-dependencies.mapd.com/mapd-deps/mapd-deps-latest.tar.xz

Resolving internal-dependencies.mapd.com (internal-dependencies.mapd.com)... 72.28.97.165

Connecting to internal-dependencies.mapd.com (internal-dependencies.mapd.com)|72.28.97.165|:443... failed: Network is unreachable.

**Comment by xuxilei** [comment]
the computer throught  two proxy to internet

**Comment by dwayneberry** [comment]
Hi

i have just tried to download this bundle from an external network and all appears to be working fine.

please review your network configuration, as this appears to be a network issue on your network side.

**Comment by dwayneberry** [comment]
If you have no luck with getting the pre built dependencies you can build your own by following the details here

https://github.com/mapd/mapd-core#centos-7

And the script here: https://github.com/mapd/mapd-core/blob/master/scripts/mapd-deps-linux.sh

**Comment by xuxilei** [comment]
in mapd-deps-linux.sh:  "download"  refer to ?

**Comment by randyzwitch** [comment]
Closing, as this appeared to be a network issue, not a MapD issue. Please feel free to open another issue if this behavior persists
