### ISSUE TITLE
JDBC driver emits many instances of Received <n> to the console

### ISSUE THREAD

**Issue by mainstreet439** [mapd/mapd-core#162]
originally noted as https://community.mapd.com/t/jdbc-driver-emits-many-instances-of-received-n-to-the-console/923

While a Java/JDBC program is running, there can be a large (i.e. 100s or 1000s) # of "Received " messages written to the console. Appears to be coming from TServiceClient

System.out.format(“Received %d%n”, new Object[] { Integer.valueOf(msg.seqid) });

**Comment by randyzwitch** [comment]
Closing this as a duplicate in lieu of #225
