### ISSUE TITLE
Memory leak in mapdql input processing loop

### ISSUE THREAD

**Issue by ptumati** [mapd/mapd-core#167]
The linenoise while loop has multiple sources of memory leaks.  (See #168 for the pull-request to fix this.)

**Case 1: The continue statement doesn't have a free() when not connected to a mapD session.  Tested by doing "-p BadPassword" and issuing "select * from foo;" (a non-sense query.)**

```
    while ((line = linenoise(prompt.c_str())) != NULL) {
      {
       TQueryResult empty;
        swap(_return, empty);
      }
      /* Do something with the string. */
      if (line[0] != '\0' && line[0] != '\\') {
        // printf("echo: '%s'\n", line);                                                                                                              
        if (context.session == INVALID_SESSION_ID) {
          std::cerr << "Not connected to any MapD databases." << std::endl;
          continue;
        }

```

**Case 2: After a thrift kSQL try, empty row_desc() also trigger 'continue' operations and create a line leak (untested).  Seemingly empty results also cause this.**

**Case 3:  \q commands also leak memory by breaking out of the loop.**

```
      } else if (line[0] == '\\' && line[1] == 'q')
        break;

```

**Comment by shtilman** [comment]
Indeed, mapdql is rather casual with freeing memory in this loop.
