### ISSUE TITLE
add disableKeywords option to get_completion_hints endpoint

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-core#170]
do this to allow for consumers the option of using a client-side SQL keywords list to reduce the number of tokens sent over the wire.

related to issue https://github.com/mapd/mapd-core/issues/150 and PR https://github.com/mapd/mapd-core/pull/142

**Comment by asuhan** [comment]
Why is it important to reduce the number of tokens sent over the wire? We're talking hundreds of bytes.

**Comment by micahstubbs** [comment]
well, it's also for convenience for the front-end.

**Comment by micahstubbs** [comment]
don't worry about this right now, think I have a quick patch figured out.  going to test it and see if I like the result.

**Comment by asuhan** [comment]
I'm not sure I understand what do you mean by convenience. Do we need to return keywords only sometimes? If yes, what's the criteria?

**Comment by micahstubbs** [comment]
good questions. 

yea, I realized that it's possible to use the table+column name hints from `get_completion_hints` in combination with the comprehensive [SQL keywords list](https://github.com/codemirror/CodeMirror/blob/master/mode/sql/sql.js#L268) from CodeMirror.  this actually give a pretty nice user experience.  

it's also an artifact of some front-end implementation choices that it's easier to supply a table+column name hints to an existing frontend library SQL hinting function than to write a custom frontend hinting function.  that's also a reason to like a mode for `get_completion_hints` that only returns **mapd**-specific tokens, like table+column names or special mapd-only SQL operators.

the criteria would be when a new argument `disableKeywords` is `true`.  they way it looks now, my front-end client would always pass `disableKeywords=true`.  (this could change if I discover some new information later)

**Comment by asuhan** [comment]
You can simply filter out the keyword hints then, the type is returned alongside the contents of the hint. Am I missing something?

**Comment by tmostak** [comment]
@micah I thought one of the issues is that CodeMirror just simply offered you all keywords without any context of what had been entered so far. The hope was that the backend supplied hints would be more contextual. Also you’ll have an isssue that we don’t support some of the SQL keywords that it might suggest. 

What’s the argument for not just using the backend supplied hints?

**Comment by micahstubbs** [comment]
@tmostak best I can tell, right now the backend hints 

1) aren't contextual yet
2) support hints for a tiny subset of SQL keywords
  
this is why I reach for existing libraries.  in the future when the backend hints are built out, we could probably do what you describe.

**Comment by micahstubbs** [comment]
@asuhan sure, that's possible.  can you link me to the line of code that sets the hint type? I saw that type code, but haven't found a key yet that tells me what category each integer type goes with 🤔

**Comment by micahstubbs** [comment]
ok, I think I can reverse engineer the hint types.  does this look correct?

| type  | category  |
|:---:|:---|
|  7 | keyword  |
|  0 | column name |
|  1 | table name   |

from what I observe in the browser console:
![hint-types-1](https://user-images.githubusercontent.com/2119400/34739679-e24cd64e-f531-11e7-83aa-ac5b7672f971.png)

![hint-types-2](https://user-images.githubusercontent.com/2119400/34739798-4e9ff09c-f532-11e7-91d4-d6f59f4e2062.png)

**Comment by micahstubbs** [comment]
also wonder, are there any other hint types that are implemented in **mapd-core** that are not shown in the able above?

**Comment by andrewseidl** [comment]
The type enum is defined at https://github.com/mapd/mapd-core/blob/9131b8db9ef8ef4e0d187134f8735c92c48f82f7/completion_hints.thrift#L3-L12

**Comment by micahstubbs** [comment]
@andrewseidl cool, thanks for that.  are the type integers that I see 0-based indices of that `TCompletionHintType`?  looks like it...

(also, how did you do this cool code snippet embedding in the comment?)

**Comment by andrewseidl** [comment]
Correct.

https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by asuhan** [comment]
@micahstubbs: It takes less than a minute to enable more keywords, I doubt we're talking about a "tiny subset", at least with respect to the SQL we support. The lists in other libraries might be comprehensive, but they're also incorrect for us. I'm sure I've missed a few, just give me a list and I'll enable all of them.

Also, the completions are somewhat context dependent, at least in my experience. What Calcite does for context-dependent completions (it uses a simplified parser for partial queries and figures out which tokens would make the query parse) is reasonable and beyond what can be done by a frontend-only library. That being said, the real-life impact of the approach might be limited, so if you could provide examples of desired behavior I'm sure we can get it done quickly.

**Comment by micahstubbs** [comment]
yep, let's iterate towards full MAPD-SQL keyword support from `get_completion_hints`.  

until then, it's nice to have alternatives to get started quickly 😄 

I'll close this issue, since learning what those completion type indices meant solved my immediate need.
