### ISSUE TITLE
completion hints wishlist

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-core#174]
will create a wishlist of improvements to the cool new `get_completion_hints` endpoint 🌱 

- [x] suggest keyword hints at 1 or more chars (3 or more right now, we think)

context improvements:
- [x] suggest valid keywords at empty string (the beginning of a session) (these could be SELECT WITH, perhaps others)
- [x] after `FROM` only suggest table name hints
- [x] complete `SELECT` and `FROM` more often? having trouble articulating when this should happen, but feel like it should be more often.
- [x] infer table names to suggest from already-typed column names.  don't always suggest all of the table and column hints (it looks like we do this right now)

**Comment by billmaimone** [comment]
@micahstubbs @mythilimapd Repeating for others what I said last night.  I saw you & @todd last night looking only at SQL editor window.  I think we should be focusing more on usage of completion hints from dashboards, which is where we had both specific customer request, and also an ability to do a better job of it.  Recalling the Jamcity comment -- typing into custom measures & dimensions is usable, as you have to mentally understand how to write SQL that will work with the statement being built for you.  And if you screw up you get a useless parse error.  One of the challenges for SQL editor is that due to (dumb) SQL grammar, user has to type column names before tables so autocomplete on columns isn't ideal.   But for a chart you already pick your data source for a chart or layer, and by chart type you know something about what columns/functions can be valid.  And in SQL editor, help is much appreciated but it's more obvious that you're building a free-form SQL statement the expectation for perfect help is lower.

**Comment by tmostak** [comment]
Elaborating on ``after FROM only suggest table name hints`` it would be nice to only offer table or column hints when they are legal. Like after I type GROUP i should only be offered BY but currently I am offered all table and columns.  Can Calcite tell us when a table/column identifier would be legal?

**Comment by asuhan** [comment]
I think Calcite does the right thing in the `GROUP` case for example, but there's logic to add our own token-based hints when we don't like the result from Calcite (for example if it's only keywords). This isn't hard to fix.

**Comment by asuhan** [comment]
https://github.com/mapd/mapd-core/pull/178 should address all but the last point.

**Comment by asuhan** [comment]
Commit 53278f4cbeb2e891e2558b3e0f0db76cd802a38a should address the last item. It doesn't prevent the other suggestions to show, but they're ranked lower in the list.

**Comment by micahstubbs** [comment]
running mapd-core at the latest commit on this branch, #400a3e3, and seeing some hints that surprise me.  will share here in case it's useful.

`SELECT * FROM ` then press `Tab` to show completion hints

I would expect to see only table names, or at least a list sorted with all the table names at the top.  instead, I see a bunch of column names:
![screen shot 2018-01-16 at 5 01 04 pm](https://user-images.githubusercontent.com/2119400/35020203-b940f9c0-fadf-11e7-89c7-b0ac804e57ec.png)

 for reference, the table names in this database are
![screen shot 2018-01-16 at 5 01 34 pm](https://user-images.githubusercontent.com/2119400/35020222-dc4326dc-fadf-11e7-9e4c-ac973593e203.png)

if I press `cmd` + `option` + `j` to open the javascript console in Chrome, I can see what the `get_completion_hints` endpoint returned for this particular hint request

![hints-from-mapd-core-1](https://user-images.githubusercontent.com/2119400/35020274-20481e32-fae0-11e7-9f08-9eb265653ee8.png)

so, the table names are there, they are just crowded out by the column names (which I think should not be there).  In this context, removing the column name hints would provide the desired behavior.  however, it's useful to observe that since hints are grouped by type, any sorting between types will be lost when the hints are sent to the client.

right now, the client presents hints naively, sorted by type in this order:

```
    // const completionHintTypes = {
    //   0: "COLUMN",
    //   1: "TABLE",
    //   2: "VIEW",
    //   3: "SCHEMA",
    //   4: "CATALOG",
    //   5: "REPOSITORY",
    //   6: "FUNCTION",
    //   7: "KEYWORD"
    // }
```

**Comment by asuhan** [comment]
Can't reproduce the issue, the server returns only table hints after the `FROM`.

**Comment by micahstubbs** [comment]
huh.  thanks for testing this.  will `rm -rf` my `mapd-core/build` dir and build again.

**Comment by micahstubbs** [comment]
ok, tried again.

@asuhan can you try this string, with the one whitespace character after the `FROM`?

`SELECT * FROM\s`

(sorry about that, I think the github markdown renderer at my whitespace before 😅 )

**Comment by asuhan** [comment]
Same, works correctly.

**Comment by micahstubbs** [comment]
looks perfect now.  I was connecting to the port for the old version 🤦‍♀️ 

<img width="1181" alt="screen shot 2018-01-16 at 10 08 03 pm" src="https://user-images.githubusercontent.com/2119400/35028230-cebdc1aa-fb09-11e7-9202-4a774a59292c.png">

**Comment by micahstubbs** [comment]
ok, it looks like this wishlist is complete for now.  I'd suggest we can close this issue as soon as PR # **Context-sensitive auto completion** https://github.com/mapd/mapd-core/pull/178 is merged

**Comment by micahstubbs** [comment]
a new wish / test case, contributed by @mythilimapd 

> `SELECT dep_delay` (if I don’t have a comma after dep_delay I would expect the next autocomplete to only show the SQL keywords)

![screen shot 2018-01-19 at 5 24 11 pm](https://user-images.githubusercontent.com/2119400/35178425-a45605a4-fd3d-11e7-9a66-0f554dc32d19.png)

**Comment by asuhan** [comment]
https://github.com/mapd/mapd-core/pull/180/ does this.

**Comment by micahstubbs** [comment]
fantastic,  nice work 🙌

**Comment by Davidiskander** [comment]
## There are some sql syntax that are good to have:
`CAST`
`AS`
`COPY`
`WITH`
`CASE`
`IN`
`DROP TABLE`
`ALTER TABLE`
`RENAME TO`

### Data_types: 
```STRING, FLOAT, INTGER, ....```

### Statistics functions 
```STDDEV_FLOAT, STDDEV_POP_FLOAT, STDDEV_SAMP_FLOAT, VARIANCE_FLOAT, VAR_POP_FLOAT, VAR_SAMP_FLOAT, CORRELATION_FLOAT, CORR_FLOAT, COVAR_POP_FLOAT, COVAR_SAMP_FLOAT```

**Comment by micahstubbs** [comment]
nice, thanks for documenting this syntax request @Davidiskander!

@asuhan what do you think about add hints for these keywords?

**Comment by asuhan** [comment]
@micahstubbs Do we actually want to allow DDL (`COPY`, `DROP TABLE`, `ALTER TABLE`, `RENAME TO`) from Immerse? It's very easy to add hints for them if we do. Also, `CAST`, `CASE` and `IN` are very easy. The rest is rather complicated to do accurately.

**Comment by Davidiskander** [comment]
DDL already functions in Immerse (SQLEditor)
<img width="998" alt="screen shot 2018-01-25 at 8 54 49 am" src="https://user-images.githubusercontent.com/10747240/35401171-a5fd4308-01ad-11e8-961b-1e1f7655300d.png">

**Comment by micahstubbs** [comment]
good question.  I'd say if DLL already works from Immerse, it would be nice to provide hints for DDL operators.  

generally, I'd like to see hints for all operators that we support where it's practical / un-complicated to add accurate contextual hints.  thanks for thinking about these new ones!

**Comment by simoneves** [comment]
+1 for DROP TABLE

**Comment by micahstubbs** [comment]
one more comment from @DennisDawson 

> when you choose ORDER it doesn't immediately give me ORDER BY. 

@asuhan sometime, it would be nice to support SQL Operators that consist of multiple words nicely, like `ORDER BY`

**Comment by randyzwitch** [comment]
@asuhan or others, can this be closed? Task list says 5 out of 5

**Comment by micahstubbs** [comment]
good point @randyzwitch!  will close this one 😄

**Comment by randyzwitch** [comment]
Thanks @micahstubbs !
