### ISSUE TITLE
cmake CUDA issue

### ISSUE THREAD

**Issue by pdiddyb** [mapd/mapd-core#18]
I think everything is installed correctly, but I cannot get past this error:
CMake Error at /usr/local/mapd-deps/20170505/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "8.0")
Call Stack (most recent call first):
  /usr/local/mapd-deps/20170505/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/mapd-deps/20170505/share/cmake-3.7/Modules/FindCUDA.cmake:1013 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)

**Comment by pdiddyb** [comment]
I was able to get it by using the run file instead of the rpm and yum.

**Comment by flowbehappy** [comment]
@pdiddyb 

Hi, I face the same error. And I cannot understand what you mean by "using the run file". Please help.
