### ISSUE TITLE
Multiple outer joins convert NULL values to 0

### ISSUE THREAD

**Issue by jirizaloudek** [mapd/mapd-core#184]
I tested the outer join support in MapD and find out an issue with converting the NULL values from right table to 0 if there is more than one join.

## How to reproduce:
Create three tables:

```
create table a (id int);
create table b (id int, val int);
create table c (id int, val int);

insert into a values(1);
insert into a values(2);
insert into a values(3);
insert into b values(1, 50);
insert into c values(2, 60);
```

## One join example:

```
select a.id, b.val from a left outer join b on a.id = b.id;
id|val
1|50
2|NULL
3|NULL
3 rows returned.
```
Returns the NULL values for `b` table as expected.

## Two joins example:

```
select a.id, b.val, c.val from a left outer join b on a.id = b.id left outer join c on a.id = c.id;
id|val|val0
1|50|NULL
2|0|60
3|0|NULL
3 rows returned.
```
The NULL values for table `b` have been converted into `0`. The NULL values are returned just for table `c`.

**Comment by asuhan** [comment]
@jirizaloudek Does this happen on master? I've just tried and results look correct.

**Comment by jirizaloudek** [comment]
@asuhan I tested it on the last release: MapD Server Version: 3.4.0-20180116-a484981 on AWS (ami-90824de9)

**Comment by asuhan** [comment]
Ok, that doesn't include the fixes. Next release should fix this problem.

**Comment by dwayneberry** [comment]
@jirizaloudek I can reproduce your issue on the current release.  The bug has been fixed in the latest code and will be available with the next full release, or you can get it now by building the open source code.

**Comment by jirizaloudek** [comment]
that's great news, thanks all for the fast response. I am closing this issue.

**Comment by dwayneberry** [comment]
Oh confusing,  overlapping responses.
