### ISSUE TITLE
Documentation: Array indexes are 1-based

### ISSUE THREAD

**Issue by bploetz** [mapd/mapd-core#188]
This was the source of a bug in our code and was somewhat surprising:

```
mapdql> select s_location, s_location[0], s_location[1], s_location[2] from stories limit 10;
s_location|EXPR$1|EXPR$2|EXPR$3
{40.760233470354, -111.88437638397}|NULL|40.760233470354|-111.88437638397
{37.1042, -113.583}|NULL|37.1042|-113.583
{40.741469601787, -111.89497265483}|NULL|40.741469601787|-111.89497265483
{34.1016151, -118.3039834}|NULL|34.1016151|-118.3039834
{40.690581566286, -111.55013580744}|NULL|40.690581566286|-111.55013580744
{33.88658, -117.5796}|NULL|33.88658|-117.5796
{37.1042, -113.583}|NULL|37.1042|-113.583
{33.88658, -117.5796}|NULL|33.88658|-117.5796
{40.637902144104, -111.47849003316}|NULL|40.637902144104|-111.47849003316
{34.44848, -119.23857}|NULL|34.44848|-119.23857
```

I had assumed arrays in MapD were 0-based indexes, but they are actually 1-based. This is not specified anywhere in the documentation that I could find (please correct me if I'm wrong), but it would be good to explicitly call this out on the Array Support page (https://www.mapd.com/docs/latest/mapd-core-guide/dml/#array-support).

**Comment by micahstubbs** [comment]
hi @bploetz, it looks we just updated the docs, adding a note about the 1-based indexing.  does this 
looks like what you would expect to see? 

<img width="771" alt="screen shot 2018-02-07 at 12 32 16 pm" src="https://user-images.githubusercontent.com/2119400/35940130-09671888-0c03-11e8-9a51-eddada9fe2f5.png">


https://www.mapd.com/docs/latest/mapd-core-guide/dml/#array-support

**Comment by bploetz** [comment]
Looks great, thanks @micahstubbs
