### ISSUE TITLE
Is SQRT function supported

### ISSUE THREAD

**Issue by lightsailpro** [mapd/mapd-core#193]
I could not find the "square root" function. Is it supported in MapD core? If not, can it be supported? Thanks a lot.

**Comment by tmostak** [comment]
That must have been an oversight on our part. Extension functions are added in this file here (https://github.com/mapd/mapd-core/blob/master/QueryEngine/ExtensionFunctions.hpp) and its very easy to add new ones (see how log is implemented). Feel free to contribute the function yourself or we can do it.

**Comment by shtilman** [comment]
It's actually converted to ^0.5 by Calcite: 
```
mapdql> select sqrt(9) from tbl;
EXPR$0
3
mapdql> explain calcite select sqrt(x) from tbl;
Explanation
LogicalSort(fetch=[1])
  LogicalProject(EXPR$0=[POWER($8, 0.5)])
    EnumerableTableScan(table=[[mapd, tbl]])
```

**Comment by lightsailpro** [comment]
Awesome! I will try.
