### ISSUE TITLE
Exception: Hash tables with more than 2B entries not supported yet

### ISSUE THREAD

**Issue by lightsailpro** [mapd/mapd-core#194]
I am testing a table with about 4 billion rows. The query involves self-join on this table. I got error: Exception: Hash tables with more than 2B entries not supported yet. Is there any workaround? What is "hash tables" here - subquery? Thanks

**Comment by dwayneberry** [comment]
It is building a hash table for the join to execute on.  This hash table is restricted to 2B entries.

The work around would be to go to a distributed set up and shard the data across several machines to keep each hash table under the 2B entries limit.
