### ISSUE TITLE
clarification on mode \cpu, \gpu, enable-watchdog = false, allow-cpu-retry = true

### ISSUE THREAD

**Issue by lightsailpro** [mapd/mapd-core#197]
I have a large query on which I am getting the following error:

"Exception: Failed to run the cardinality estimation query: Query couldn't keep the entire working set of columns in GPU memory"

I already have "enable-watchdog = false", "allow-cpu-retry = true" in the configuration file. Is it supposed to try automatically in small batches in \gpu mode, the try \cpu mode if gpu does not work well? 

To work around this, I had to manually switch to cpu mode using \cpu before running query. 

Also, is there way to check how much GPU ram a query need in order to run with enable-watchdog = false or enable-watchdog = true ?

**Comment by dwayneberry** [comment]
Currently the cardinality estimation does not drop back to CPU if it fails.  So in your case the query exits at cardinality_estimate on GPU.

enable-watchdog has no effect on how much memory is going to be used by a query.

We do not currently pre-calculate/estimate how much memory a given query is going to need, this is something we do plan to do, it just hasn't been done yet.

**Comment by lightsailpro** [comment]
In \cpu mode, I got the following error indeed:

"Exception: Failed to get a high quality cardinality estimation"

Is there any workaround?

**Comment by dwayneberry** [comment]
I suspect you are requesting a huge number of groups.
Can you share the query and the cardinality individually of all the group by columns

**Comment by lightsailpro** [comment]
I have a table t1 with 3 columns (c1 int, c2 text encoding dict, c3 int) with about 4 billion rows. There are about 0.7 million unique c1 values. c2 averages about 8 characters. There are another table t2 with same structure as t1, but just 500 c1 values. The error occurred when joining two tables on c1 with some calculated column.

--It will be great if you add features like RDMS "explain plan" to show the execution plans with RAM requirement 
--If the query plan does not fit GPU or CPU ram, can the execution be done on disk or in small batches in GPU or CPU. You mentioned that cardinality estimation  was always done in GPU, why is that?

So is there any way to bypass the error and run the query with current mapd version?

**Comment by dwayneberry** [comment]
Please share the the query statement.

There is basic execution plan information from `explain calcite select ....` and additionally `explain select ....`

The initial cardinality estimate is done on whatever device the initial query is requested to run on.  A failure to run the cardinality on GPU currently does not allow the query to fall back to cpu.

**Comment by lightsailpro** [comment]
Here are the table structure, query and error messages. Please help.

--TABLE definition:
t1: (c1 int, c2 text encoding dict, c3 int)
t2: (c1 int, c2 text encoding dict, c3 int)

--Sample query:

select count(*)
from
(
   SELECT t1.c1 as c11, t2.c1 as c12, SUM(t1.c3 * t2.c3) AS dotp, SUM(1) as jdotp
   FROM t1
       INNER JOIN t2 on t1.c2 = t2.c2
   WHERE t1.c1 <> t2.c1
   GROUP BY t1.c1, t2.c1
) t;

--ERROR:

*when t1 has same amount of data as t2 (4 billions rows):
"Exception: Hash tables with more than 2B entries not supported yet"

*when t1 only has about 500 distinct c1 values:
Exception: Failed to run the cardinality estimation query: Query couldn't keep the entire working set of columns in GPU memory

**Comment by asuhan** [comment]
@lightsailpro If we do the math, we have 4B rows x 6 columns x 4 bytes worth of input data, which is 96GB. It doesn't fit in your K40's 12GB of memory.

We could make this query to run on the K40 by allowing data do be swapped in and out of GPU memory via PCI Express, there's already a mechanism for it which we don't expose to user. But we've decided not to, because in such cases (a lot less GPU memory than needed) it's not worth running the query on GPU at all. You should still be able to run the query in CPU mode.

**Comment by lightsailpro** [comment]
Thanks for your help and analysis.

In case 1), even with CPU mode (\cpu), I still have this error: 

"Exception: Hash tables with more than 2B entries not supported yet". Hopefully future version will have this restriction removed.

In case 2), with \cpu mode, no "2B entries" exception probably because the outer table is much smaller. The query run for a while, then get the following error:

"Exception: Failed to get a high quality cardinality estimation"

**Comment by asuhan** [comment]
How many groups do you expect the results to have? If `t1.c1` and `t2.c1` are independent, you might be running out of linear probabilistic counter's precision and it wouldn't matter a lot if we're talking too many groups to handle (on a single machine) anyway. If the actual number of groups is reasonable, we might be able to fix this.

Also, even 64GB of host memory isn't enough for what you're trying to do, just the input data involved is 96GB.

**Comment by lightsailpro** [comment]
In a single batch, t1 and t2 actually have same data with more than 0.5 million (t1.c1) x 0.5 million (t2.c1) pairs of (t1.c1, t2.c1).  But we can do the calculation in smaller batches incrementally with around n (t1.c1) x 0.5 million t2.c1 pairs with "n" from 500, or 1000, the larger the better, depending on what mapd core engine can handle and finish the query in reasonable time e.g. less than 10 minutes. 

The current query is running on hive with map-reduce. I feel mapd core can do the calculation more efficiently.

So with current mapd core version, is there any solution to handle 500 x 500000 groups of "t1.c1 t2.c1"?

**Comment by asuhan** [comment]
Sharding on the c1 column of t2 would work, but you need more than one server (or something like 8 x K80 cards).

**Comment by baldeaglelabs** [comment]
Which NVIDIA cards can MapD use?
I understand it is optimized for NVIDIA Tesla P40 and P100
https://www.mapd.com/docs/latest/getting-started/hwRefCfgGuide/

Will MapD use other GPUs as well though at a lower level of performance?
thanks

**Comment by randyzwitch** [comment]
Closing this issue. If this continues to be a problem with one of our current 4.x releases, please feel free to open another issue
