### ISSUE TITLE
Race condition in parallel build with Parser/parser.h

### ISSUE THREAD

**Issue by wesm** [mapd/mapd-core#198]
I experienced a build failure in a from scratch build with `make -j4` where a compilation unit was looking for `Parser/parser.h` but that part of the dependency graph had not been build yet.

**Comment by wesm** [comment]
I'm having some other problems related to the Parser module:

```
[  4%] Built target rerun_cmake
[  6%] Built target poly2tri
[  7%] Built target sqlite3
[  7%] Built target SqliteConnector
[  8%] Built target Utils
[  9%] Built target StringDictionary
[ 10%] Built target Fragmenter
[ 11%] Built target Calcite
[ 13%] Built target Catalog
[ 14%] Generating Parser.cpp
[ 14%] Built target ParserFiles
[ 14%] Built target ScannerFiles
[ 14%] Built target Analyzer
[ 15%] Built target CudaMgr
[ 21%] Built target DataMgr
[ 21%] Built target Chunk
[ 23%] Built target Shared
[ 24%] Built target CsvImport
[ 51%] Built target QueryEngine
[ 52%] Built target Planner
[ 53%] Generating Parser.cpp
[ 53%] Generating Parser.cpp
[ 53%] Building CXX object Parser/CMakeFiles/Parser.dir/Parser.cpp.o
g++-4.9: error: /home/wesm/code/goai/mapd-core/build/Parser/Parser.cpp: No such file or directory
g++-4.9: fatal error: no input files
compilation terminated.
make[2]: *** [Parser/CMakeFiles/Parser.dir/Parser.cpp.o] Error 4
make[1]: *** [Parser/CMakeFiles/Parser.dir/all] Error 2
make: *** [all] Error 2
```

I run `make ParserFiles` but the Parser.cpp file is not created in the right place:

```
$ make ParserFiles
[100%] Generating Parser.cpp
[100%] Built target ParserFiles
19:13 ~/code/goai/mapd-core/build  (arrow-tip-upgrade)$ ls -l Parser/
total 96
drwxrwxr-x 5 wesm wesm  4096 Feb 24 19:08 CMakeFiles
-rw-rw-r-- 1 wesm wesm  1132 Feb 24 18:48 cmake_install.cmake
-rw-rw-r-- 1 wesm wesm 15336 Feb 24 18:48 Makefile
-rw-rw-r-- 1 wesm wesm 72753 Feb 24 18:48 Scanner.cpp
```

**Comment by dwayneberry** [comment]
What platvorm are you trying to build on.  Do you have the latest dependencies https://github.com/mapd/mapd-core#dependencies

**Comment by wesm** [comment]
I'm using CMake 3.10 installed via conda-forge (on Ubuntu 14.04). I can try with CMake 3.3 to see if that fixes

**Comment by andrewseidl** [comment]
Do you have `bison++` and `flex++` available in your PATH?

**Comment by wesm** [comment]
Yes -- though it seems there was something wrong with my `bison++` binary, so I rebuilt from source and now things seem to be working. Will reopen if I hit a reproducible problem

**Comment by andrewseidl** [comment]
Glad to hear it.

A similar issue came up internally last week, so I might just start vendoring `bison++` instead of relying on it being installed elsewhere on the system. Only adds a second or two to the initial build and should prevent a bunch of issues, like this one.
