### ISSUE TITLE
Build Error on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by hung135** [mapd/mapd-core#20]
awk: symbol lookup error: /usr/local/mapd-deps/20170531/lib/libreadline.so.6: undefined symbol: UP
awk: symbol lookup error: /usr/local/mapd-deps/20170531/lib/libreadline.so.6: undefined symbol: UP
awk: symbol lookup error: /usr/local/mapd-deps/20170531/lib/libreadline.so.6: undefined symbol: UP
gawk: symbol lookup error: /usr/local/mapd-deps/20170531/lib/libreadline.so.6: undefined symbol: UP
configure: WARNING: oops, unrecognised float format: 
gawk: symbol lookup error: /usr/local/mapd-deps/20170531/lib/libreadline.so.6: undefined symbol: UP
config.status: error: could not create demos/pexpr-config.h

**Comment by dwayneberry** [comment]
Please share more detail of the steps you went through to get to this error.

Can you share the details when you built the required dependencies.

**Comment by JohnnyLChang** [comment]
I can build successfully on Ubuntu 16.10

Scanning dependencies of target StreamInsert
[ 98%] Building CXX object SampleCode/CMakeFiles/StreamInsert.dir/StreamInsert.cpp.o
[ 99%] Linking CXX executable ../bin/StreamInsert
[ 99%] Built target StreamInsert
Scanning dependencies of target StreamInsertSimple
[ 99%] Building CXX object SampleCode/CMakeFiles/StreamInsertSimple.dir/StreamInsertSimple.cpp.o
[100%] Linking CXX executable ../bin/StreamInsertSimple
[100%] Built target StreamInsertSimple
Scanning dependencies of target generate_cert
[100%] Built target generate_cert
johnny@ubuntu:~/mapd-core$ uname -r
4.8.0-52-generic
johnny@ubuntu:~/mapd-core$ uname -m
x86_64
johnny@ubuntu:~/mapd-core$ cat /etc/issue
Ubuntu 16.10 \n \l

**Comment by hung135** [comment]
I will try to reproduce.  With as many dependencies, have you guys thought about creating a Vagrant file that would take the build process from beginning to end?  I will try to make one so I can retrace each step.

**Comment by hung135** [comment]
Was able to build on ubuntu server following the steps.  Was not able to build on 16.04 Desktop.  Will close this issue and reopen one for the Ubuntu Desktop when I get more details.
