### ISSUE TITLE
there is C#(.NET) driver?

### ISSUE THREAD

**Issue by billschen** [mapd/mapd-core#202]
I user C#(.NET), I had installed  [MapD](https://www.mapd.com/platform/downloads/) and read [Client Interfaces](https://www.mapd.com/docs/latest/mapd-core-guide/client/).
But can't find .NET client. I want to use C# to insert data to Map.

**Comment by RalphLoen** [comment]
Hello Bill,

MapD does not currently support a .NET driver, although this is certainly possible from an architectural standpoint.

Regards,
Ralph

**Comment by billschen** [comment]
OK,thank you~,I use[ java](https://www.mapd.com/docs/latest/mapd-core-guide/jdbc/#resources) now~
