### ISSUE TITLE
https://internal-dependencies.mapd.com/mvn/ not available~ Building JDBC driver

### ISSUE THREAD

**Issue by ssainz** [mapd/mapd-core#203]
Hello,

I noticed that an older version of mapdjdbc does not support Statement.getWarnings() 

I notice is supported in latest version, but, when I try to build jar: 

mvn package -rf :mapdjdbc

I get error: 

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] mapdjdbc
[INFO] calcite
[INFO] utility
[INFO] mapd
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building mapdjdbc 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://internal-dependencies.mapd.com/mvn/com/mapd/thrift/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.mapd:thrift:1.0-SNAPSHOT/maven-metadata.xml from/to MapD Internal Dependencies (https://internal-dependencies.mapd.com/mvn/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer com.mapd:thrift:1.0-SNAPSHOT/maven-metadata.xml from https://internal-dependencies.mapd.com/mvn/ was cached in the local repository, resolution will not be reattempted until the update interval of MapD Internal Dependencies has elapsed or updates are forced. Original error: Could not transfer metadata com.mapd:thrift:1.0-SNAPSHOT/maven-metadata.xml from/to MapD Internal Dependencies (https://internal-dependencies.mapd.com/mvn/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Downloading: https://internal-dependencies.mapd.com/mvn/com/mapd/thrift/1.0-SNAPSHOT/thrift-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] mapdjdbc ........................................... FAILURE [  2.547 s]
[INFO] calcite ............................................ SKIPPED
[INFO] utility ............................................ SKIPPED
[INFO] mapd ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.642 s
[INFO] Finished at: 2018-03-29T12:58:58-04:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mapdjdbc: Could not resolve dependencies for project com.mapd:mapdjdbc:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.mapd:thrift:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for com.mapd:thrift:jar:1.0-SNAPSHOT: Could not transfer artifact com.mapd:thrift:pom:1.0-SNAPSHOT from/to MapD Internal Dependencies (https://internal-dependencies.mapd.com/mvn/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by dwayneberry** [comment]
The thrift code is generated as part of the larger build process.

We do not currently support building just the jdbc without having built the rest of the MapD system
