### ISSUE TITLE
COPY from s3 can only process the first 1000 documents in a bucket

### ISSUE THREAD

**Issue by andrewrimmer** [mapd/mapd-core#219]
Only the first 1000 documents are processed from the s3 bucket. The MapD Copy command returns successfully and with 0 rejections. However this is very misleading because potentially 1000s of documents may have been ignored.

I would guess this is caused by not checking that more results are available using the GetIsTruncated flag on the ListObjectsRequest result.

> The ListObjectsResult object has two values that will help you: GetIsTruncated and GetNextMarker. GetIsTruncated tells you if you've reached the end of the result set. If you haven't reached the end, you fetch the next set of results by setting the marker on the request (ListObjectsRequest::SetMarker) to be the value of ListObjectsResult::GetNextMarker from the result of the previous request.

**Comment by randyzwitch** [comment]
@andrewrimmer Just wanted to follow-up with you on this, this bug should be resolved in our 4.1.1 release which will come out in the next several days. I will leave this issue open until it's released, then close it

**Comment by randyzwitch** [comment]
Released:

https://www.mapd.com/docs/latest/7_0_release.html#4-1-1-released-september-4-2018
