### ISSUE TITLE
centos 7 Missing Python Libs?

### ISSUE THREAD

**Issue by hung135** [mapd/mapd-core#22]
I followed the steps to build for Centos.  Looks like I got all the way down to the end and got this:
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG - Failed
-- Looking for __func__
-- Looking for __func__ - found
-- Looking for fopen in c
-- Looking for fopen in c - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for __cxa_throw in stdc++
-- Looking for __cxa_throw in stdc++ - found
-- Looking for __i686__
-- Looking for __i686__ - not found
-- Looking for __i386__
-- Looking for __i386__ - not found
-- Compiler-RT supported architectures: x86_64
-- Looking for rpc/xdr.h
-- Looking for rpc/xdr.h - found
-- Looking for tirpc/rpc/xdr.h
-- Looking for tirpc/rpc/xdr.h - not found
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG - Success
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG - Success
-- Performing Test COMPILER_RT_HAS_FREESTANDING_FLAG
-- Performing Test COMPILER_RT_HAS_FREESTANDING_FLAG - Success
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD - Success
-- Builtin supported architectures: x86_64
-- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS
-- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS - Success
-- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK
-- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK - Success
-- check-xray-fdr does nothing.
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Clang version: 4.0.0
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
-- LLD version: 4.0.0
CMake Error at /usr/local/mapd-deps/20170608/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/mapd-deps/20170608/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/mapd-deps/20170608/share/cmake-3.7/Modules/FindPythonLibs.cmake:255 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  tools/lldb/cmake/modules/LLDBConfig.cmake:179 (find_package)
  tools/lldb/CMakeLists.txt:4 (include)

-- Configuring incomplete, errors occurred!
See also "/home/vagrant/github/mapd-core/scripts/build.llvm-4.0.0/CMakeFiles/CMakeOutput.log".
See also "/home/vagrant/github/mapd-core/scripts/build.llvm-4.0.0/CMakeFiles/CMakeError.log".

**Comment by billmaimone** [comment]
@andrewseidl Any idea what's wrong here?

**Comment by dwayneberry** [comment]
@hung135 Did this occur while you were trying to build the dependencies?

if you are using centos 7 you can grab the dependencies already built and ready for you.  Please see instructions here https://github.com/mapd/mapd-core#centos-7

**Comment by andrewseidl** [comment]
You might need to install package `python-devel`. I'll update the docs once I get a chance to reproduce.

That being said, as @dwayneberry mentioned, the easiest and quickest way to get up and running is to use the prebuilt dependencies.

**Comment by hung135** [comment]
Thanks guys.
@dwayneberry those were the directions I followed. Manualy many times. I must be missing something.
I also made a vagrant file just so I can destroy and re-create the evironment from scratch each time.  https://github.com/hung135/vagrant_mapd_centos/blob/master/Vagrantfile.  I'll keep at it until I get it to compile.  Any other guidence would be appreciated.

**Comment by dwayneberry** [comment]
You do not need to manually build the dependencies at all you can download for centos 7 a prebuild set of dependencies

from the instructions I point to above:

Next download and install the prebuilt dependencies:

```
curl -OJ https://internal-dependencies.mapd.com/mapd-deps/deploy.sh
sudo bash deploy.sh
```

These dependencies will be installed to a directory under /usr/local/mapd-deps. The deploy.sh script also installs Environment Modules in order to simplify managing the required environment variables. Log out and log back in after running the deploy.sh script in order to active Environment Modules command, module.

The mapd-deps environment module is disabled by default. To activate for your current session, run:
```
module load mapd-deps
```
To disable the mapd-deps module:
```
module unload mapd-deps
```
