### ISSUE TITLE
No Backend Rendering Support

### ISSUE THREAD

**Issue by suyongheng** [mapd/mapd-core#24]
Will this community edition support backend rendering?

**Comment by asuhan** [comment]
Yes, I think we'll offer it as a binary blob (it's closed source). @andrewseidl knows more about it.

**Comment by andrewseidl** [comment]
Correct, we plan on offering backend rendering support as a closed source, non-commercial use plugin, but we do not currently have a timeline for when that will be available.

For the time being you can download the free Community Edition, which does include backend rendering support: https://www.mapd.com/products/downloads/
