### ISSUE TITLE
Privileges are not correctly propagated from roles to users

### ISSUE THREAD

**Issue by omveda** [mapd/mapd-core#246]
as mapd superuser
```
create table my_table (i1 int, i2 int);

insert into my table values (1,2);
insert into my_table values (1,2);
insert into my_table values (3,4);

create view my_view as select i1 from my_table;

create user my_user (password = 'password', is_super = 'false');
create role my_role;
grant my_role to my_user;
grant all on view my_view to my_role;
grant all on dashboard  to my_role;
```
Here my_view is a view that was created earlier.

Logged into MapD as “./bin/mapdql -u my_user -p password”
mapdql> select * from my_view; 
Worked successfully.

But if I go to Immerse DataManager, I am not able to see my_view and also cannot "open" the dashboard that been created for my_view. The reason could be the discrepancy in privilege propagation here:
mapdql> \privileges my_role
 (dashboard): create delete view edit
my_view (view): create drop select insert update delete
mapdql> \privileges my_user //Returns empty
mapdql> \v                             //Returns empty

**Comment by kchu-mapd** [comment]
Verified using:
The Server Version Number  : 4.1.0dev-20180813-85f7e6f06d

Followed the original bug description and confirmed the following are working as expected:
1. my_view shows up in Immerse Data Manager.
2. my_view works in dashboard
3. \privileges my_role and \privileges my_user return correct privileges. 

mapdql> \privileges my_role
 (dashboard): create delete view edit
my_view (view): create drop select insert update delete
mapdql> \privileges my_user
my_user dashboard (dashboard): create delete view edit
