### ISSUE TITLE
Error: Exception: Overflow or underflow

### ISSUE THREAD

**Issue by domoritz** [mapd/mapd-core#248]
I'm running an aggregation query against metis but get this error: `Error: Exception: Overflow or underflow`. 

The query:

```sql
SELECT
    cast((depdelay - -20.177777777777777) / 0.17777777777777778 as int) AS keyActiveX,
    cast((arrdelay - -20.177777777777777) / 0.17777777777777778 as int) AS keyActiveY,
    cast((airtime - 0) / 20 as int) as key,
    count(*) AS cnt
  FROM flights_donotmodify
  WHERE -20.177777777777777 <= depdelay AND depdelay < 60 AND -20.177777777777777 <= arrdelay AND arrdelay < 60 AND 0 <= airtime AND airtime < 500 AND true
  GROUP BY keyActiveX, keyActiveY, key
```

**Comment by domoritz** [comment]
Thank you @shtilman! What is the accepted precision? I am generating queries automatically.

**Comment by domoritz** [comment]
Could this be related to #250?

**Comment by shtilman** [comment]
Yes, same issue.
These literals are taken in as decimals with high precision. If you compare them to ints, or do math with ints, the latter would have to be upscaled to the same precision, e.g. `depdelay` would have to be multiplied by 10^15. That's the source of overflows. Depends on `depdelay` values whether you would overflow or not.
Two ways of dealing with this:
- reduce precision of you literals
- or you can cast your literals to float and not worry about precision, for example:
`SELECT cast((depdelay - cast(-20.177777777777777 as float) / cast(0.17777777777777778 as float)) as integer)  from flights limit 10;`  the math will be done in float but precision will still be lost in the cast to integer

**Comment by domoritz** [comment]
`cast(-20.177777777777777 as float)` works perfectly. Thanks!
