### ISSUE TITLE
Implementing a distributed cluster

### ISSUE THREAD

**Issue by david4096** [mapd/mapd-core#26]
I've set up a few instances of MapD across a cluster and made sure they can see each other via the hostnames in the cluster.conf. However, when loading to the node configured as the aggregator, I don't see the string-server or any leaves getting data.

Other than setting the cluster.conf, `string-server=` or `cluster=` keys what other steps are needed to implement a MapD cluster? I'm using CPU only.

Thanks!

**Comment by dwayneberry** [comment]
MapD distributed support is only offered in the Enterprise Edition.  What edition are you running?

**Comment by david4096** [comment]
From source here, thanks. I must have missed that in the docs.
