### ISSUE TITLE
DATEDIFF doesn't understand some months with 31 days

### ISSUE THREAD

**Issue by testvinder** [mapd/mapd-core#261]
I found a serious error in the results of query. I used the following query:
 `select check_in, check_out, DATEDIFF('day', A.check_in, A.check_out) as duration from sparse_full_2019_3`

Among the results were the following:
`2019-03-30    2019-04-06    6` (should be 7)
`2019-03-24    2019-03-31   6`  (should be 7)
`2019-03-24    2019-03-30    6` (correct)

**Comment by shtilman** [comment]
Seems to be working fine:
```
mapdql> create table ddiff (d1 DATE, d2 DATE);
mapdql> insert into ddiff values(DATE '2019-03-24', DATE '2019-03-31');
mapdql> insert into ddiff values(DATE '2019-03-30', DATE '2019-04-06');
mapdql> insert into ddiff values(DATE '2019-03-24', DATE '2019-03-30');
mapdql> select DATEDIFF('day', d1, d2) from ddiff;
EXPR$0
7
7
6
```

**Comment by shtilman** [comment]
If you're working with TIMESTAMPS, you have to be mindful of the time too.
DATEDIFF counts whole days:
```
mapdql> select DATEDIFF('day', TIMESTAMP '2019-03-30 0:00:00', TIMESTAMP '2019-04-06 0:00:00') from test limit 1;
EXPR$0
7
mapdql> select DATEDIFF('day', TIMESTAMP '2019-03-30 0:00:01', TIMESTAMP '2019-04-06 0:00:00') from test limit 1;
EXPR$0
6
```

**Comment by testvinder** [comment]
I can reproduce your results (MapD 4.0). But notice another strange things that possibly explain my initial result. If I do `select * from ddiff;`
![image](https://user-images.githubusercontent.com/13538640/44837220-50973400-ac39-11e8-92ab-d137b038a2bc.png)
Notice how one of the rows have time zone GMT+0200 and rest have GMT+0100.

**Comment by shtilman** [comment]
Yes, DATEDIFF doesn't account for time zone differences. Probably a good idea to convert all date/timestamp columns to a single timezone for consistency.

I think this issue can be closed. Please open a new one if you encounter any other DATEDIFF issues.
