### ISSUE TITLE
compile failed in centos

### ISSUE THREAD

**Issue by dongAxis** [mapd/mapd-core#266]
i got an error when i compile the mapd:

Results :

```
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

QueryEngine/libQueryEngine.a(TopKSort.o): In function `inline_int_null_val(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)':
/home/yifeng.dongyifeng/mapd-core/QueryEngine/SqlTypesLayout.h:91: undefined reference to `decimal_to_int_type(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/initdb] Error 1
make[1]: *** [CMakeFiles/initdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target mapd_java_components
```

but decimal_to_int_type is exactly in libShared.a

Thanks in advance~

**Comment by dongAxis** [comment]
more error log:

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

QueryEngine/libQueryEngine.a(TopKSort.o): In function `inline_int_null_val(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)':
/home/yifeng.dongyifeng/mapd-core/QueryEngine/SqlTypesLayout.h:91: undefined reference to `decimal_to_int_type(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/initdb] Error 1
make[1]: *** [CMakeFiles/initdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target mapd_java_components
[100%] Linking CXX executable bin/mapd_server
ThriftHandler/libthrift_handler.a(MapDHandler.cpp.o): In function `loadArrowStream':
/home/yifeng.dongyifeng/mapd-core/ThriftHandler/MapDHandler.cpp:1985: undefined reference to `arrow::Status::ToString[abi:cxx11]() const'
/home/yifeng.dongyifeng/mapd-core/ThriftHandler/MapDHandler.cpp:1985: undefined reference to `arrow::Status::ToString[abi:cxx11]() const'
/home/yifeng.dongyifeng/mapd-core/ThriftHandler/MapDHandler.cpp:1991: undefined reference to `arrow::Status::ToString[abi:cxx11]() const'
/home/yifeng.dongyifeng/mapd-core/ThriftHandler/MapDHandler.cpp:1991: undefined reference to `arrow::Status::ToString[abi:cxx11]() const'
QueryEngine/libQueryEngine.a(ResultSetConversion.cpp.o): In function `arrow::make_field(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&, std::shared_ptr<arrow::Array> const&)':
/home/yifeng.dongyifeng/mapd-core/QueryEngine/ResultSetConversion.cpp:347: undefined reference to `arrow::field(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<arrow::DataType> const&, bool, std::shared_ptr<arrow::KeyValueMetadata const> const&)'
QueryEngine/libQueryEngine.a(TopKSort.o): In function `inline_int_null_val(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)':
/home/yifeng.dongyifeng/mapd-core/QueryEngine/SqlTypesLayout.h:91: undefined reference to `decimal_to_int_type(SQLTypeInfoCore<ArrayContextTypeSizer, ExecutorTypePackaging> const&)'
QueryEngine/libQueryEngine.a(ArrowUtil.cpp.o): In function `arrow_status_throw(arrow::Status const&)':
/home/yifeng.dongyifeng/mapd-core/QueryEngine/ArrowUtil.cpp:25: undefined reference to `arrow::Status::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mapd_server] Error 1
make[1]: *** [CMakeFiles/mapd_server.dir/all] Error 2
make: *** [all] Error 2

**Comment by andrewseidl** [comment]
What version of gcc are you using? In the same terminal used to build, run `g++ --version && which g++`

**Comment by dongAxis** [comment]
my default gcc is 6.4.0 , but cuda 8.0 can only support gcc 4.x, so use the 4.x t compile mapd.

**Comment by andrewseidl** [comment]
Ok, that would explain it: MapD Core is currently written in C++14, which is not well supported in GCC 4.x. 5.1 is the minimum supported version.

CUDA 8 does support GCC 5 if you're able to build with that, though CUDA 9+ would be preferred.

Alternatively there's a CMake option `MAPD_HOST_COMPILER` which gets passed on to nvcc's `-ccbin` option, but mixing gcc 4 with 5+ code probably won't work due to the ABI change in 5.

**Comment by dongAxis** [comment]
Thanks, but it has an new error:
I compile the curl and install it to "/usr/local/mapd-deps/20180917"

[ 98%] Linking CXX executable bin/mapd_server
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `VSICURLResetHeaderAndWriterFunctions':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:1038: undefined reference to `curl_easy_setopt'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `ClearCache':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:2943: undefined reference to `curl_multi_cleanup'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `MultiPerform':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:986: undefined reference to `curl_multi_add_handle'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:992: undefined reference to `curl_multi_perform'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:1019: undefined reference to `curl_multi_remove_handle'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `GetCurlMultiHandleFor':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:2634: undefined reference to `curl_multi_init'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `VSICurlSetOptions(void*, char const*, char const* const*)':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:8426: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:8434: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:8441: undefined reference to `curl_easy_setopt'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `VSICurlMergeHeaders(curl_slist*, curl_slist*)':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:8457: undefined reference to `curl_slist_append'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:8461: undefined reference to `curl_slist_free_all'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `DeleteObject':
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6253: undefined reference to `curl_easy_cleanup'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6184: undefined reference to `curl_easy_init'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6186: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6187: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6193: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6197: undefined reference to `curl_easy_setopt'
/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6199: undefined reference to `curl_easy_setopt'
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o):/home/jenkins-slave/workspace/mapd-deps/scripts/gdal-2.3.1/port/cpl_vsil_curl.cpp:6203: more undefined references to `curl_easy_setopt' follow
/usr/local/mapd-deps/20180917/lib/libgdal.a(cpl_vsil_curl.o): In function `DeleteObject':

**Comment by dongAxis** [comment]
I already solve this problem . thanks
