### ISSUE TITLE
llvm on OSX

### ISSUE THREAD

**Issue by jonbaer** [mapd/mapd-core#4]
OSX 10.11.6 + Homebrew 1.2 (+ using mapd-deps-osx.sh)

GroupByAndAggregate.h:34:10: fatal error: 
      'llvm/IR/Function.h' file not found
#include <llvm/IR/Function.h>

Any ideas for a fix?  Looking at http://stackoverflow.com/questions/26246769/including-llvm-value-h-not-found do I need a different version of llvm (4.0)?

**Comment by asuhan** [comment]
Do you have `llvm-config` in your path? Version 4.0 should be fine.

**Comment by jonbaer** [comment]
Thanks, I am up + running, seems that brew --prefix got confused on an older copy while I was trying to figure it out (4.0 is fine) ...

brew --prefix llvm
/usr/local/Cellar/llvm/4.0.0_1
(previous)
brew --prefix llvm@3.7
/usr/local/opt/llvm@3.7

**Comment by bluealert** [comment]
I have removed llvm using `brew remove llvm` and the directory "llvm" is also deleted. but when I run `brew --prefix llvm`, the output is always: `/usr/local/Cellar/llvm/5.0.0`.

Does someone know the reason? How can I change the output of `brew --prefix llvm` ?

**Comment by jonbaer** [comment]
This seems to happen every LLVM release where they push the previous version down into /usr/local/opt for some reason.  I think what should happen is the mapd-deps-osx.sh script should use `llvm-config --prefix` (vs. `brew --prefix`) - your output for --prefix is stuck at which version is linked.

You can try the following:
`brew unlink llvm`
`brew install llvm`
`brew link --force llvm`

**Comment by bluealert** [comment]
@jonbaer Thank you.

I run `brew help --prefix`, it's output is as follow:
```
brew --prefix:
    Display Homebrew's install path. *Default:* /usr/local

brew --prefix formula:
    Display the location in the cellar where formula is or would be installed.
```
