### ISSUE TITLE
frontend compilation error?

### ISSUE THREAD

**Issue by tomodachi21** [mapd/mapd-core#40]
I successfully installed all of the dependencies but when I go to **make -j 4** it looks to crash at a part that is called "frontend". Is there an explicit cause for this? I am using the =debug configuration

```
root:/home/ubuntu/mapd-core/build# make -j 4
[  0%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/common/shapes.cc.o
[  0%] Generating gen-cpp/MapD.cpp, gen-cpp/MapD.h, gen-cpp/mapd_constants.cpp, gen-cpp/mapd_types.cpp
[  0%] Generating ../gen-cpp/CalciteServer.cpp, ../gen-cpp/calciteserver_constants.cpp, ../gen-cpp/calciteserver_types.cpp
[  1%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/advancing_front.cc.o
Scanning dependencies of target calciteserver_thrift
[  1%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/cdt.cc.o
[  2%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/sweep.cc.o
Scanning dependencies of target mapd_thrift
[  2%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/sweep_context.cc.o
[  3%] Linking CXX static library libpoly2tri.a
[  3%] Built target poly2tri
[  3%] Building C object ThirdParty/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
[  4%] Linking C static library libsqlite3.a
[  5%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/CalciteServer.cpp.o
[  6%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/MapD.cpp.o
[  6%] Built target sqlite3
[  7%] Building CXX object Utils/CMakeFiles/Utils.dir/StringLike.cpp.o
[  7%] Building CXX object Utils/CMakeFiles/Utils.dir/Regexp.cpp.o
[  8%] Building CXX object Utils/CMakeFiles/Utils.dir/ChunkIter.cpp.o
[  8%] Linking CXX static library libUtils.a
[  8%] Built target Utils
[  9%] Building CXX object Fragmenter/CMakeFiles/Fragmenter.dir/InsertOrderFragmenter.cpp.o
[  9%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/calciteserver_constants.cpp.o
[  9%] Linking CXX static library libFragmenter.a
[ 10%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/calciteserver_types.cpp.o
[ 10%] Built target Fragmenter
[ 10%] Linking CXX static library libcalciteserver_thrift.a
[ 11%] Generating Parser.cpp
/home/ubuntu/mapd-core/Parser/parser.y contains 5 shift/reduce conflicts and 2 reduce/reduce conflicts.
[ 11%] Built target ParserFiles
[ 12%] Generating Scanner.cpp
[ 12%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/mapd_constants.cpp.o
[ 12%] Built target calciteserver_thrift
[ 12%] Built target ScannerFiles
[ 13%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/mapd_types.cpp.o
[ 13%] Building CXX object CudaMgr/CMakeFiles/CudaMgr.dir/CudaMgr.cpp.o
[ 13%] Building CXX object Shared/CMakeFiles/Shared.dir/Datum.cpp.o
[ 15%] Building CXX object Shared/CMakeFiles/Shared.dir/timegm.cpp.o
[ 15%] Linking CXX static library libCudaMgr.a
[ 15%] Building CXX object Shared/CMakeFiles/Shared.dir/mapd_glob.cpp.o
[ 15%] Built target CudaMgr
[ 16%] Creating directories for 'frontend'
[ 17%] Building CXX object Shared/CMakeFiles/Shared.dir/StringTransform.cpp.o
[ 17%] Linking CXX static library libmapd_thrift.a
[ 17%] Performing download step (download, verify and extract) for 'frontend'
-- File already exists but no hash specified (use URL_HASH):
  file='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
   timeout='none'
-- Using src='https://builds.mapd.com/frontend/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
[ 17%] Linking CXX static library libShared.a
-- Configuring done
[ 17%] Built target mapd_thrift
[ 18%] Generating bin/mapd_web_server
/bin/sh: 1: /usr/bin/go: not found
make[2]: *** [bin/mapd_web_server] Error 127
make[1]: *** [CMakeFiles/mapd_web_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 18%] Built target Shared
-- [download 1% complete]
-- [download 3% complete]
-- Generating done
-- [download 4% complete]
-- [download 5% complete]
-- [download 7% complete]
-- Build files have been written to: /home/ubuntu/mapd-core/build
[ 18%] Built target rerun_cmake
-- [download 8% complete]
-- [download 9% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
     dst='/home/ubuntu/mapd-core/build/external/src/frontend'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 18%] No patch step for 'frontend'
[ 19%] No update step for 'frontend'
[ 20%] No configure step for 'frontend'
[ 20%] No build step for 'frontend'
[ 20%] No install step for 'frontend'
[ 21%] Completed 'frontend'
[ 21%] Built target frontend
make: *** [all] Error 2
```

**Comment by asuhan** [comment]
You need the Go compiler (`golang` package in Ubuntu). We should add this to our readme, @andrewseidl.

**Comment by tomodachi21** [comment]
Okay but this is a problem because **graceful** requires go1.3+ so when I uninstall golang and installed go1.8 to successfully install **graceful** it works... when I reinstall golang it switches to 

`go version go1.2.1 linux/amd64` and I'm pretty sure this breaks graceful

And now I get this error:
`-- Build files have been written to: /home/ubuntu/mapd-core/build
[  0%] Generating ../gen-cpp/CalciteServer.cpp, ../gen-cpp/calciteserver_constants.cpp, ../gen-cpp/calciteserver_types.cpp
[  0%] Generating gen-cpp/MapD.cpp, gen-cpp/MapD.h, gen-cpp/mapd_constants.cpp, gen-cpp/mapd_types.cpp
[  0%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/common/shapes.cc.o
[  1%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/advancing_front.cc.o
Scanning dependencies of target calciteserver_thrift
[  1%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/cdt.cc.o
[  2%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/sweep.cc.o
Scanning dependencies of target mapd_thrift
[  2%] Building CXX object ThirdParty/poly2tri/CMakeFiles/poly2tri.dir/poly2tri/sweep/sweep_context.cc.o
[  3%] Linking CXX static library libpoly2tri.a
[  3%] Built target poly2tri
[  3%] Building C object ThirdParty/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
[  4%] Linking C static library libsqlite3.a
[  5%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/CalciteServer.cpp.o
[  5%] Built target sqlite3
[  6%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/MapD.cpp.o
[  6%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/calciteserver_constants.cpp.o
[  7%] Building CXX object Utils/CMakeFiles/Utils.dir/StringLike.cpp.o
[  7%] Building CXX object Utils/CMakeFiles/Utils.dir/Regexp.cpp.o
[  8%] Building CXX object Calcite/CMakeFiles/calciteserver_thrift.dir/__/gen-cpp/calciteserver_types.cpp.o
[  8%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/mapd_constants.cpp.o
[  9%] Building CXX object Utils/CMakeFiles/Utils.dir/ChunkIter.cpp.o
[  9%] Linking CXX static library libUtils.a
[ 10%] Building CXX object CMakeFiles/mapd_thrift.dir/gen-cpp/mapd_types.cpp.o
[ 10%] Linking CXX static library libcalciteserver_thrift.a
[ 10%] Built target Utils
[ 10%] Linking CXX static library libmapd_thrift.a
[ 10%] Built target calciteserver_thrift
[ 11%] Generating Parser.cpp
/home/ubuntu/mapd-core/Parser/parser.y contains 5 shift/reduce conflicts and 2 reduce/reduce conflicts.
[ 12%] Building CXX object Fragmenter/CMakeFiles/Fragmenter.dir/InsertOrderFragmenter.cpp.o
[ 12%] Built target ParserFiles
[ 13%] Generating Scanner.cpp
[ 13%] Linking CXX static library libFragmenter.a
[ 13%] Built target ScannerFiles
[ 13%] Building CXX object CudaMgr/CMakeFiles/CudaMgr.dir/CudaMgr.cpp.o
[ 14%] Linking CXX static library libCudaMgr.a
[ 14%] Built target Fragmenter
[ 14%] Built target mapd_thrift
[ 15%] Creating directories for 'frontend'
[ 15%] Building CXX object Shared/CMakeFiles/Shared.dir/Datum.cpp.o
[ 16%] Building CXX object Shared/CMakeFiles/Shared.dir/timegm.cpp.o
[ 16%] Performing download step (download, verify and extract) for 'frontend'
-- File already exists but no hash specified (use URL_HASH):
  file='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
   timeout='none'
-- Using src='https://builds.mapd.com/frontend/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
[ 16%] Building CXX object Shared/CMakeFiles/Shared.dir/mapd_glob.cpp.o
[ 16%] Built target CudaMgr
[ 17%] Building CXX object Shared/CMakeFiles/Shared.dir/StringTransform.cpp.o
[ 18%] Generating bin/mapd_web_server
[ 18%] Linking CXX static library libShared.a
[ 18%] Built target Shared
-- Configuring done
[ 18%] Generating ../java/thrift/src/gen/com/mapd/thrift/server/MapD.java, ../java/thrift/src/gen/com/mapd/thrift/server/TRow.java
[ 19%] Generating ../java/thrift/src/gen/com/mapd/thrift/calciteserver/CalciteServer.java
[ 20%] Generating bin/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar, bin/mapdjdbc-1.0-SNAPSHOT-jar-with-dependencies.jar, bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar
-- [download 1% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
# gopkg.in/tylerb/graceful.v1
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:46: undefined: http.ConnState
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:253: srv.Server.ConnState undefined (type *http.Server has no field or method ConnState)
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:253: undefined: http.ConnState
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:255: undefined: http.StateNew
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:257: undefined: http.StateIdle
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:259: undefined: http.StateClosed
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:259: undefined: http.StateHijacked
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:367: srv.Server.ConnState undefined (type *http.Server has no field or method ConnState)
go/src/gopkg.in/tylerb/graceful.v1/graceful.go:402: srv.SetKeepAlivesEnabled undefined (type *Server has no field or method SetKeepAlivesEnabled)
-- [download 35% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 53% complete]
-- [download 54% complete]
-- Generating done
-- [download 55% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 66% complete]
-- Build files have been written to: /home/ubuntu/mapd-core/build
[ 20%] Built target rerun_cmake
-- [download 67% complete]
-- [download 68% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
[ 21%] Building CXX object ThirdParty/googletest/CMakeFiles/gtest.dir/gmock-gtest-all.cc.o
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
[ 21%] Linking CXX static library libgtest.a
make[2]: *** [bin/mapd_web_server] Error 2
make[1]: *** [CMakeFiles/mapd_web_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/ubuntu/mapd-core/build/external/src/mapd2-dashboard-v2-f23da32-unofficial-prod.zip'
     dst='/home/ubuntu/mapd-core/build/external/src/frontend'
-- extracting... [tar xfz]
[ 21%] Built target gtest
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 22%] No update step for 'frontend'
[ 22%] No patch step for 'frontend'
[ 23%] No configure step for 'frontend'
[ 23%] No build step for 'frontend'
[ 23%] No install step for 'frontend'
[ 24%] Completed 'frontend'
[ 24%] Built target frontend

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[ 24%] Built target mapd_java_components
make: *** [all] Error 2
`

**Comment by dwayneberry** [comment]
@tomodachi21 what version of unbuntu are you using?

**Comment by tomodachi21** [comment]
@dwayneberry Ubuntu 14.04 (AWS EC2 instance)

**Comment by dwayneberry** [comment]
@tomodachi21 so we don't recommend using anything older than 16.04, is it possible for you to move to a more current release.

**Comment by tomodachi21** [comment]
I will do an update and see if that fixes it with golang-1.8-go.... thanks will let you know.

**Comment by tomodachi21** [comment]
In total wasted about 10+ hrs trying to compile this on 14.04... switching between VMs and reimaging. Upgrading to 16.04 did fix everything.

Thanks again for your contribution to open-source. Look forward to seeing this project evolve. If you could please put a notation on the install page (DO NOT USE 14.04) it will save other people like me the frustration of trying to install. Unfortunately most people using DeepLearning libraries are still on 14.04 because of the resiliency (AWS DeepLearning image is 14.04) so I would suspect a lot of people are going to try to install this on 14.04.

Thanks again

**Comment by tomodachi21** [comment]
Note: Still having issues with 16.04 where it is complaining that it is unable to find **libnetcdf.so.7**
From what I am seeing it looks like 16.04 is standard with .11 not .7 ~ trying to figure out if this is a hardcoded decency or can be changed more easily. I got the Xenial package from here:

https://launchpad.net/ubuntu/xenial/+source/netcdf

```
./usr/lib/x86_64-linux-gnu/libnetcdf.so.11
./usr/lib/x86_64-linux-gnu/libnetcdf.so.11.0.0

```
```
root@/home/ubuntu/mapd-core/build# ../startmapd
Backend TCP:  localhost:9091
Backend HTTP: localhost:9090
Frontend Web: localhost:9092
Calcite TCP: localhost:9093
- sleeping for 5s while server starts
./bin/mapd_server: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory
Terminated
```

**Comment by tomodachi21** [comment]
I hardcoded a patch by copying the newer versions as the older versions but I'm getting this issue for all of the following files:
```
libnetcdf.so.7
libhdf5.so.7
libgif.so.4
```

I installed newer versions for 16.04 (Xenial) and renamed them to the files listed above

**Comment by tomodachi21** [comment]
Really odd - after I am able to get it compiled installed an all the above errors supressed it complains that is is unable to detect any GPUs. Noted I am using CUDA7.5 on an AWS EC2 instance with 16.04 and a Tesla K80:
```
root@/home/ubuntu/mapd-core/build# ../startmapd
Backend TCP:  localhost:9091
Backend HTTP: localhost:9090
Frontend Web: localhost:9092
Calcite TCP: localhost:9093
- sleeping for 5s while server starts
./bin/mapd_server: /usr/local/lib/libgdal.so.1: no version information available (required by ./bin/mapd_server)
E0705 00:37:32.448576  1377 MapDHandler.cpp:154] This build isn't CUDA enabled, will run on CPU
Thrift: Wed Jul  5 00:37:32 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Wed Jul  5 00:37:32 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Wed Jul  5 00:37:32 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Wed Jul  5 00:37:32 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Wed Jul  5 00:37:32 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Wed Jul  5 00:37:33 2017 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
E0705 00:37:33.189343  1377 MapDHandler.cpp:186] No GPUs detected, falling back to CPU mode
```

The GPU is installed and working correctly on CUDA7.5

```
root@/home/ubuntu/mapd-core/build# nvidia-smi
Wed Jul  5 00:44:55 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
| N/A   75C    P0    62W / 149W |      0MiB / 11439MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by dwayneberry** [comment]
It would appear your cmake process did not set the cuda flag. in the build.  You currently have built a cpu only version.

**Comment by dwayneberry** [comment]
run ``ccmake ..``` in your build directory,  and make sure you have cuda set

**Comment by tomodachi21** [comment]
Thanks that was a great help - yes they were set OFF. Recompiling: note for those using 16.04 you will get an error about the version of gcc and g++ you are using, you can fix that by doing this

$ sudo ln -s /usr/bin/gcc-4.9 /usr/local/cuda-7.5/bin/gcc
$ sudo ln -s /usr/bin/g++-4.9 /usr/local/cuda-7.5/bin/g++

Thanks to 
https://github.com/NervanaSystems/neon/issues/246

**Comment by asuhan** [comment]
@tomodachi21 Indeed, CUDA 7.5 doesn't support gcc 5 and higher. Alternatively, you could upgrade to CUDA 8.

**Comment by tomodachi21** [comment]
Thanks @asuhan  will look into that, had cuda-8.0 installed on my 14.04 before updating to 16.04 but it seems to have been removed an installing it again is not easy. Getting another error now trying to work through:

```
[ 89%] Linking CXX executable bin/mapd_server
/usr/bin/ld: warning: libboost_program_options.so.1.58.0, needed by /usr/local/mapd-deps/lib/libfolly.so, may conflict with libboost_program_options.so.1.64.0
/usr/bin/ld: warning: libboost_filesystem.so.1.58.0, needed by /usr/local/mapd-deps/lib/libfolly.so, may conflict with libboost_filesystem.so.1.64.0
/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by /usr/local/mapd-deps/lib/libfolly.so, may conflict with libboost_system.so.1.64.0
/usr/bin/ld: warning: libboost_regex.so.1.58.0, needed by /usr/local/mapd-deps/lib/libfolly.so, may conflict with libboost_regex.so.1.64.0
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgdal.so: undefined reference to `nc_inq_var_chunking'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgdal.so: undefined reference to `nc_def_var_chunking'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgdal.so: undefined reference to `nc_def_var_deflate'
collect2: error: ld returned 1 exit status
CMakeFiles/mapd_server.dir/build.make:161: recipe for target 'bin/mapd_server' failed
make[2]: *** [bin/mapd_server] Error 1
CMakeFiles/Makefile2:121: recipe for target 'CMakeFiles/mapd_server.dir/all' failed
make[1]: *** [CMakeFiles/mapd_server.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by asuhan** [comment]
You have both 1.58 and 1.64 versions of Boost in your library path. You have a few options:

1. Uninstall Boost 1.64 through apt-get.
2. Build mapd using exclusively what you get through apt-get, don't use `mapd-deps` at all (just remove the folder).
3. Play with library paths so that 1.64 isn't seen by the linker and the loader.

We've written the instructions with a clean installation of 16.04 in mind, plus CUDA, plus our `mapd-deps`. Once you start pulling upstream libraries, there'll be conflicts.

**Comment by dwayneberry** [comment]
I just did a build form clean machine on a p2.xlarge instance to double check our instructions:

AMI from market place : ```ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170619.1```

update machine:

```
sudo apt update
sudo apt upgrade
sudo reboot
```
install cuda:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
 sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb 
 sudo apt-get update
 sudo apt-get install cuda
```
install our dependencies (copied from readme here https://github.com/mapd/mapd-core)
```
sudo apt update
sudo apt install -y \
    build-essential \
    cmake \
    cmake-curses-gui \
    git \
    clang \
    clang-format \
    llvm \
    llvm-dev \
    libboost-all-dev \
    libgoogle-glog-dev \
    golang \
    libssl-dev \
    libevent-dev \
    default-jre \
    default-jre-headless \
    default-jdk \
    default-jdk-headless \
    maven \
    libncurses5-dev \
    binutils-dev \
    google-perftools \
    libdouble-conversion-dev \
    libevent-dev \
    libgdal-dev \
    libgflags-dev \
    libgoogle-perftools-dev \
    libiberty-dev \
    libjemalloc-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    zlib1g-dev \
    autoconf \
    autoconf-archive

sudo apt build-dep -y thrift-compiler
VERS=0.10.0
wget http://apache.claz.org/thrift/$VERS/thrift-$VERS.tar.gz
tar xvf thrift-$VERS.tar.gz
pushd thrift-$VERS
./configure \
    --with-lua=no \
    --with-python=no \
    --with-php=no \
    --with-ruby=no \
    --prefix=/usr/local/mapd-deps
make -j $(nproc)
sudo make install
popd

VERS=1.11.3
wget --continue https://github.com/Blosc/c-blosc/archive/v$VERS.tar.gz
tar xvf v$VERS.tar.gz
BDIR="c-blosc-$VERS/build"
rm -rf "$BDIR"
mkdir -p "$BDIR"
pushd "$BDIR"
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local/mapd-deps \
    -DBUILD_BENCHMARKS=off \
    -DBUILD_TESTS=off \
    -DPREFER_EXTERNAL_SNAPPY=off \
    -DPREFER_EXTERNAL_ZLIB=off \
    -DPREFER_EXTERNAL_ZSTD=off \
    ..
make -j $(nproc)
sudo make install
popd

VERS=2017.04.10.00
wget --continue https://github.com/facebook/folly/archive/v$VERS.tar.gz
tar xvf v$VERS.tar.gz
pushd folly-$VERS/folly
/usr/bin/autoreconf -ivf
./configure --prefix=/usr/local/mapd-deps
make -j $(nproc)
sudo make install
popd

VERS=1.21-45
wget --continue https://github.com/jarro2783/bisonpp/archive/$VERS.tar.gz
tar xvf $VERS.tar.gz
pushd bisonpp-$VERS
./configure --prefix=/usr/local/mapd-deps
make -j $(nproc)
sudo make install
popd

VERS=0.4.1
wget --continue https://github.com/apache/arrow/archive/apache-arrow-$VERS.tar.gz
tar -xf apache-arrow-$VERS.tar.gz
mkdir -p arrow-apache-arrow-$VERS/cpp/build
pushd arrow-apache-arrow-$VERS/cpp/build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DARROW_BUILD_SHARED=off \
    -DARROW_BUILD_STATIC=on \
    -DCMAKE_INSTALL_PREFIX=/usr/local/mapd-deps \
    -DARROW_BOOST_USE_SHARED=off \
    -DARROW_JEMALLOC_USE_SHARED=off \
    ..
makej
sudo make install ####### I changed this as I needed to add the sudo ######
popd
```
one change here as you need to do sudo on final arrow install (note the ###### 2 lines above) 

Export environemt
```
LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/lib/jvm/default-java/jre/lib/amd64/server:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/mapd-deps/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/mapd-deps/lib64:$LD_LIBRARY_PATH

PATH=/usr/local/cuda/bin:$PATH
PATH=/usr/local/mapd-deps/bin:$PATH

export LD_LIBRARY_PATH PATH
```

get mapd code ad build it
```
git clone https://github.com/mapd/mapd-core.git
cd mapd-core
mkdir build
cd build
cmake ..
make -j
```
run and enjoy

```
../startmapd
```
the whole process including building the required dependencies and starting the AWS machine took about 40 minutes.

as @asuhan has pointed out I suspect you have a very mixed install environment which you need to manage your library path and dependency path more carefully with.

**Comment by dwayneberry** [comment]
closing this issue as no further info available.  Appears issues were environmental
