### ISSUE TITLE
sql_execute_gpudf` returns 'Exception: CHAR is not supported in temporary table.') for TEXT columns

### ISSUE THREAD

**Issue by a-ghorbani** [mapd/mapd-core#43]
If a column type is a `TEXT` or `[VAR]CHAR` and is queried via `sql_execute_gpudf` returns an error like `TMapDException(error_msg='Exception: CHAR is not supported in temporary table.')`
Despite the fact that the compression type is `ENCODING DICT`.

Though, I expect from (`mapd-core/QueryEngine/InputMetadata.cpp` line ~76-79)
```
bool uses_int_meta(const SQLTypeInfo& col_ti) {
   return col_ti.is_integer() || col_ti.is_decimal() || col_ti.is_time() || col_ti.is_boolean() ||
              (col_ti.is_string() && col_ti.get_compression() == kENCODING_DICT);
}
```
if the type is string (any `(CHAR || TEXT || VARCHAR)`) and the encoding is `DICT` it should evaluate the column as INT meta.

**Comment by a-ghorbani** [comment]
To reproduce the error:

1.
```
mapdql> CREATE TABLE test_table (col1 TEXT ENCODING DICT);
mapdql> INSERT INTO test_table VALUES ('r1');
mapdql> INSERT INTO test_table VALUES ('r2');
```
2.
```
from thrift.protocol import TBinaryProtocol
from thrift.protocol import TJSONProtocol
from thrift.transport import TSocket
from thrift.transport import THttpClient
from thrift.transport import TTransport
from pymapd import MapD

def get_client(host_or_uri, port, http):
  if http:
    transport = THttpClient.THttpClient(host_or_uri)
    protocol = TJSONProtocol.TJSONProtocol(transport)
  else:
    socket = TSocket.TSocket(host_or_uri, port)
    transport = TTransport.TBufferedTransport(socket)
    protocol = TBinaryProtocol.TBinaryProtocol(transport)

  client = MapD.Client(protocol)
  transport.open()
  return client

db_name = 'mapd'
user_name = 'mapd'
passwd = 'HyperInteractive'
hostname = 'localhost'
portno = 9091

client = get_client(hostname, portno, False)
session = client.connect(user_name, passwd, db_name)
print('Connection complete')

client.sql_execute_gpudf(session, "select * from test_table",device_id=0, first_n=-1)
```

**Comment by andrewseidl** [comment]
Are you building Core yourself or using a prebuilt Community Edition? Text support in GDF/Arrow dataframes was introduced about a week ago around commit baf29451a and will be included in next week's Community release.

GDF support is still in alpha and subject to some API changes. Similarly [mapd/pymapd](https://github.com/mapd/pymapd) is still under development, though it is a convenient way to access the underlying Thrift API without having to generate & fix up the bindings yourself. (cc mapd/pymapd#14)

If you'd like to continue playing around, I've pushed a temporary branch with the updated Thrift bindings to my fork at [andrewseidl/pymapd@thrift-20170708](https://github.com/andrewseidl/pymapd/tree/thrift-20170708) . To use :

    pip install git+https://github.com/andrewseidl/pymapd@thrift-20170708

And then change the `client.sql_execute_gpudf()` in your Python script to instead be:

    client.sql_execute_df(session, "select * from test_table", device_type=MapD.TDeviceType.GPU, device_id=0, first_n=-1)

You'll also need a recent build of mapd-core. Current build of master (commit 9738335e81a3ea8d1036a69af705765beb0deb73) is available at https://goo.gl/1eGAz9 .

**Comment by a-ghorbani** [comment]
Awesome @andrewseidl! That works now \m/

But it seems `libgdf_cffi==v0.1.0a1.dev` is not compatible with the changes.
```
results = client.sql_execute_df(session, "select * from test_table", device_type=MapD.TDeviceType.GPU, device_id=0, first_n=-1)

import numpy as np
from numba import cuda
from numba.cuda.cudadrv import drvapi
from pygdf.gpuarrow import GpuArrowReader
from pygdf.dataframe import DataFrame

ipc_handle = drvapi.cu_ipc_mem_handle(*results.df_handle)
ipch = cuda.driver.IpcHandle(None, ipc_handle, size=results.df_size)
ctx = cuda.current_context()
dptr = ipch.open(ctx)

dtype = np.dtype(np.byte)
darr = cuda.devicearray.DeviceNDArray(shape=dptr.size, strides=dtype.itemsize, dtype=dtype, gpu_data=dptr)

reader = GpuArrowReader(darr)
```
returns
```
---------------------------------------------------------------------------
MetadataParsingError                      Traceback (most recent call last)
<ipython-input-6-f416c114051b> in <module>()
----> 1 reader = GpuArrowReader(darr)

/home/appuser/pygdf/pygdf/gpuarrow.py in __init__(self, gpu_data)
    113         self._nodes = []
    114 
--> 115         self._open()
    116 
    117     #

/home/appuser/pygdf/pygdf/gpuarrow.py in _open(self)
    146 
    147     def _open(self):
--> 148         nodelist, dataptr = self._parse_metdata()
    149 
    150         for dctnode in nodelist:

/home/appuser/pygdf/pygdf/gpuarrow.py in _parse_metdata(self)
    185                 error = ffi.string(raw_error).decode()
    186                 _logger.error('IPCParser failed: %s', error)
--> 187                 raise MetadataParsingError(error)
    188 
    189             # get schema as json

MetadataParsingError: ParseError: schema should not have a body

```
I'll see if I can get it work.

**Comment by a-ghorbani** [comment]
This issue basically can be closed.
It is addressed here: https://github.com/mapd/pymapd/issues/14 in https://github.com/mapd/pymapd/pull/16.
