### ISSUE TITLE
Add support for Truncate

### ISSUE THREAD

**Issue by dwayneberry** [mapd/mapd-core#49]
Add ```TRUNCATE TABLE <TABLENAME>``` to product.

result of truncate:

Table definition exists for table but all data on disk and in memory is removed.
Will currently remove data from dictionary but there is an open question of whether we may want an option to keep dictionary.

**Comment by billmaimone** [comment]
Not a great idea to purge the dictionary if it's shared, but maybe the truncate is going to be followed by reloading with updated comment and substantially same dictionary encodings.  Maybe this and shared dictionary means there should be something like a clean or truncate dictionary?

**Comment by dwayneberry** [comment]
closed with 45f8069ac34ba1b4b07c7759ed822f44397f6f44
