### ISSUE TITLE
Remove our special aiias handling as Calcite 1.13 should support this directly

### ISSUE THREAD

**Issue by dwayneberry** [mapd/mapd-core#51]
Currenty we process and manage aliases in sql ourselves via manipulation in the Calcite parser interface.  We should not have to do this as Calcite 1.13 should now allow for aliases in group by etc..

Remove our code and confirm all works with native Calcite.

**Comment by asuhan** [comment]
Is this fixed by efd1e5504aa482e9c39a169dd7f6085d9b704189?

**Comment by dwayneberry** [comment]
This is closed with https://github.com/mapd/mapd-core/commit/efd1e5504aa482e9c39a169dd7f6085d9b704189
