### ISSUE TITLE
Supporting Geospatial Operations

### ISSUE THREAD

**Issue by harshada-chavan** [mapd/mapd-core#58]
Hello,

Currently, MapD does not support a variety of geo-spatial operations such as spatial kNN queries, spatial join queries, etc. Since, these queries are compute intensive, GPUs will be tremendously beneficial for boosting their performance. I (as a part of my PhD work), am working towards adding this functionality in MapD-core and planning to release it to the community. I am currently understanding the code.

[Here](https://community.mapd.com/t/documentation-for-mapd-core-for-developers/442)'s a post from mapd-core forum where I has posted my queries related to code docs. I am creating an issue (as suggested by @aaron_mapd) here to get more help. I am willing to work with the dev team to better understand the existing code of MapD-core, designing my solution, and releasing it. Any help in this regard will be greatly appreciated!

Thanks,
Harshada

**Comment by shtilman** [comment]
Hi Harshada,

Welcome to the MapD community!

In case you missed it, we do have some geospatial features in the works: 
https://github.com/mapd/mapd-core/blob/master/ROADMAP.md#gis
Hopefully you'll be able to build upon this functionality, once it lands. 

Spatial kNN in particular could be implemented through sorting by ST_Distance() to the neighbors, in ascending order, and then taking the top K to get just the nearest ones.

It would be great if you could share technical details on all the queries you'd like MapD to support. Maybe a technical specification, use cases, etc? If you start developing, please share your design first, let's coordinate our efforts to avoid duplication. And of course let us know if you need any assistance.

Regards,
Dmitri

**Comment by harshada-chavan** [comment]
Hi Dmitri,

Thanks for the help. I will share my plane with the team.

Could you please let me know which files contain the implementation for the existing geospatial operators such as ST_Distance?

Thanks,
-Harshada

**Comment by shtilman** [comment]
Hi Harshada,

This is work in progress, I will point you to the changes once they land in mapd-core.

Thanks,
Dmitri

**Comment by Masutani** [comment]
Do you have any kind of spatial indexing like R-tree or KD-tree  in MapD ?

**Comment by VrajPandya** [comment]
Currently we don't have many indexing data-structures specially not R-tree or KD-trees. If you feel you can contribute to the project we would love to support your efforts.

**Comment by dfernan** [comment]
Hi, I have two tables, a shapefile and a table of records with lat, lon.  Is it possible to do a spatial join such that for each point I know into which polygon it falls into?  Also, what's the status of this, plans to release them soon?

**Comment by shtilman** [comment]
```
mapdql> SELECT ST_X(ST_ENDPOINT(ST_GeomFromText('LINESTRING(-118.243683 34.052235)', 4326))) from geo22 limit 1;
EXPR$0
-118.243683

mapdql> SELECT ST_X(ST_ENDPOINT(ST_GeomFromText('LINESTRING(34.052235 -118.243683)', 4326))) from geo22 limit 1;
Exception: Imported WGS84 latitude -118.243683 is out of bounds

mapdql> SELECT ST_X(ST_ENDPOINT(ST_GeomFromText('LINESTRING(234.052235 -118.243683)', 4326))) from geo22 limit 1;
Exception: Imported WGS84 longitude 234.052235 is out of bounds

mapdql> SELECT ST_X(ST_ENDPOINT('LINESTRING(234.052235 -118.243683)')) from geo22 limit 1;
EXPR$0
234.052235
```

**Comment by randyzwitch** [comment]
Closing this; MapD does now support selected geospatial operations. As we develop our roadmap, we'll consider adding these types of spatial queries
