### ISSUE TITLE
JDBC download

### ISSUE THREAD

**Issue by renderit** [mapd/mapd-core#66]
Hi is there a download available for mapd jdbc driver? (without building the whole program) 
I'm trying to use the [SQL importer](https://www.mapd.com/docs/latest/mapd-core-guide/loading-data/#sql-importer) for postgres to mapd
I'm using docker for both postgres and mapd so trying to avoid installing system wide stuff

**Comment by dwayneberry** [comment]
SQL Importer does not need the MapD JDBC driver to run.  It talks to MapD natively.  It needs a JDBC driver for the source database you are going to export from.

As an aside the jdbc driver ```mapdjdbc-1.0-SNAPSHOT-jar-with-dependencies.jar``` should be available in your bin directory of your server.

**Comment by renderit** [comment]
@dwayneberry Thanks for the prompt reply. Yes, the jar in the bin is what I was looking for. I have a postgres database running in a docker container and a mapd in another container.  Is `mapdjdbc-1.0-SNAPSHOT-jar-with-dependencies.jar` available in the git repo? Any recommendations on proceeding with this?

**Comment by dwayneberry** [comment]
@renderit 

As mentioned above SQLImporter does not need the mapd jdbc driver.

`mapdjdbc-1.0-SNAPSHOT-jar-with-dependencies.jar` will be available in your bin directory in your dockers image, but it is not needed to run `SQLImporter`

I'm not sure if you still have a question?  Please clarify the question if you are waiting on a response?

**Comment by dwayneberry** [comment]
Closing as no further info available
