### ISSUE TITLE
No OpenCL Support

### ISSUE THREAD

**Issue by mgregoro** [mapd/mapd-core#7]
Why are you guys all using Nvidia's proprietary API to do all this cool stuff?!

**Comment by asuhan** [comment]
I cannot promise anything, but this might change soon. We don't depend on CUDA that much, we have room to add support for other graphic cards. The code generation should work with minor changes, also memory allocation and data transfer should be easy to port to OpenCL. We also rely on Thrust for radix sort, which means we need to roll our own or use the HIP transpiler (https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP).

**Comment by m1mc** [comment]
This is not as good and handy as `thrust::radix_sort`: https://github.com/KhronosGroup/SyclParallelSTL/blob/master/include/sycl/algorithm/sort.hpp

**Comment by gstoner** [comment]
We are going to bring MAPD to ROCm platform.  We have lot more to talk about soon.  We are very excited by the Open Sourcing of MAPD it fits with our philosophy of bringing GPU computing forward.

**Comment by asuhan** [comment]
@gstoner We're looking forward to this and happy to help with it.

**Comment by gstoner** [comment]
I look forward to the help

**Comment by randyzwitch** [comment]
Closing this issue for now, but please feel free to open another issue if this is still a problem.
