### ISSUE TITLE
Immerse not rendering BIGINT values correctly

### ISSUE THREAD

**Issue by owenrh** [mapd/mapd-core#74]
Hi,

I’m seeing some unexpected behaviour around BIGINTs. [I’m running MapD v3.2.2 on Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1030-aws x86_64).]

If I create a table as follows:

_CREATE TABLE some_ints( intval BIGINT );_

then insert a row as follows:

_INSERT INTO some_ints VALUES(4489949424181064562);_

if I then select the contents of that table, in Immerse, I get a single row with the value being 4489949424181064700.

However, if I perform the select in mapdql it works as expected.

**Comment by dwayneberry** [comment]
This issue is to do with Java scripts handling  everything as a double. 64bit ints get truncated to the 52/53bit mantissa.  This is an immerse client issue.  Will close this backend issue.
