### ISSUE TITLE
JDBC related code isn't serializable

### ISSUE THREAD

**Issue by baank** [mapd/mapd-core#77]
Since you guys don't have a Spark DataSource we need to do the following in order to do updates i.e. we can't just use standard Spark JDBC.

```
dataframe.mapPartition {
        val statement = connection.prepareStatement(s"insert into table ?")
        statement.setString(1,columnValue)
}
```

Problem here is that com.mapd.jdbc.MapDPreparedStatement and almost everything in com.map.jdbc isn't serializable.

**Comment by baank** [comment]
The more difficult to fix issue is that the Thrift generated MapD Client is not serializable.

Which means right now you can't do updates in MapD with Spark.

**Comment by randyzwitch** [comment]
Closing in lieu of #84, as this is a technical detail of the feature request for the Spark adapter
