### ISSUE TITLE
How to let Spark access GPU Data Frame (GDF) directly?

### ISSUE THREAD

**Issue by fleapapa** [mapd/mapd-core#79]
Is there any way for Spark to access GDF like accessing Parquet files rather than like accessing an external SQL database via JDBC? 

Not sure if i understand it correctly but the former approach seems much faster, because it will treat MapD as a distributed file system rather than a SQL database. When there are millions/billions rows, it avoids huge data serialization overhead.

**Comment by asuhan** [comment]
Not sure what you mean, do no operations in MapD and just use it to read columns? That wouldn't benefit in any way from having GPUs.

**Comment by fleapapa** [comment]
The benefit i can think of is that the huge ecosystem behind Spark becomes available to MapD. 
Also, treating MapD like Parquet files actually delegates SQL functionality to Spark SQL. For example, MapD does not support table join. Through Spark SQL, it does.

**Comment by fleapapa** [comment]
Having Spark in the picture of MapD won't lose the advantage of having GPUs. See https://databricks.com/blog/2016/10/27/gpu-acceleration-in-databricks.html

**Comment by asuhan** [comment]
The main reason we're building this from scratch is the traditional one: query execution and data must be in the same address space to achieve speed. It's not clear to me which operations can actually run on GPU in Spark and I'd rather not speculate. But, as a rule of thumb, a very deep amount of integration is needed to actually get good results. That amount of integration would be the moral equivalent of fusing Spark and MapD into a single project, which isn't reasonable.

Also, MapD does support table join. It's a matter of it not being complete / friendly enough, but we're working hard on fixing it. We even support arbitrary loop joins if the watchdog flag is disabled, but the main goal is to focus on queries which can actually scale / execute interactively and avoid baseline algorithms which would send the server spinning for many minutes.

**Comment by fleapapa** [comment]
> That amount of integration would be the moral equivalent of fusing Spark and MapD into a single project, which isn't reasonable.

It seems to me that, MapD core looks like the GPU version of fusion of Apache Phoenix and Kudu projects. If i understand it correctly, Spark can access the data in Kudu's columnar store (https://kudu.apache.org/docs/developing.html#_kudu_integration_with_spark) more efficient than it accesses Phoenix's SQL columnar database via JDBC. 

Function-wise the part of source code of Kudu that handles columnar storage looks similar to that of MapD, so abstracting that part of MapD and adding an Spark adapter interface on top of the part like what Kudu has done should make get good results, i guess.

One fact hard to ignore is that more and more enterprises move toward Hadoop/Spark no more just for only batch analytics but also for real-time analytics.

**Comment by asuhan** [comment]
I'm fairly confident MapD will be able to "attach" to alternative storage in the not too distant future. Yes, I've looked into Kudu, prototyped a few things and it's definitely feasible to use it as an additional storage. The exact time line is not clear, but that integration point makes a lot of sense. I'm not arguing against it, quite the opposite; it'll happen.

**Comment by fleapapa** [comment]
> I've looked into Kudu / Arrow / Parquet, prototyped a few things and it's definitely feasible to use an alternative storage (without converting to our own storage by importing it). 

My point is the opposite. Letting others (especially SPARK) to attach MapD as an alternative storage seems less efforts and more benefits :)

**Comment by tmostak** [comment]
Generally MapD acts as an accelerator for other stores of record. With MapD several hundred times faster than Spark (http://tech.marksblogg.com/benchmarks.html), and with GPU memory relatively more expensive than CPU RAM or storage, I don't see how it would make sense to put MapD "behind" Spark. Certainly the opposite makes sense to us and is a common use case.

**Comment by fleapapa** [comment]
> With MapD several hundred times faster than Spark (http://tech.marksblogg.com/benchmarks.html), 
Definitely SPARK+Parquet can't compete with MapD on SQL query speed with warm data already in GPU memory. 

However, the big number of developers as well as the fast-growing ecosystem surrounding Spark/Hadoop should make certain senses to put MapD behind Spark (not just via JDBC... ["Why not JDBC?"](https://phoenix.apache.org/phoenix_spark.html) )

**Comment by fleapapa** [comment]
Quoted
> with GPU memory relatively more expensive than CPU RAM or storage,

That concern is true for most "developers" or those interested audiences who can't afford many GPUs to warm up their entire big data sets but may have a few 100s GB (not TBs) CPU memory to cache portions of the data, MapD and SPARK actually fall back to the same ground -- both need to load "cold" data into CPU memory **once in a while** depending on query patterns. Consider most applications with many concurrent queries hitting different ranges of the data sets. In these commonly seen use cases, "more expensive" GPU seems to help little.

For example, on my VM with 170M rows, MapD and Spark perform equally well (~30sec) on **the first** execution of query "select count(*) from (select max(trip_time_in_secs) from trips where trip_time_in_secs > 10 group by trip_time_in_secs)". A summary of comparison follows:

database               1st query             2nd+ queries
=====================================
MapD                     35 secs               0.05 sec
SPARK/Parquet     30 secs               30 secs
Clickhouse              4  secs               0.4 sec

Because living or competing (or both) with SPARK is more of belief than technical, i am closing this issue.

**Comment by archenroot** [comment]
I think this will get soon another hot topic (still was and is). There is announced RAPIDS framework with cuDF which Databricks guys are picking up and integrate in Spark. I myself work on Java bindings (They support Python mostly at moment) for whole RAPIDS framework (its not really big...at moment).

From they other directon there exists already Spark accelerated in memory database (SQL like) SnappyData. Once RAPIDS integrates with Spark, it will be only matter of time until this feature (GPU acceleration) gets propagated into SnappyData and viola we have another GPU accelerated db which out of box support RAM and VRAM shared space (although VRAM is preferred).

Do you plan some work towards Spark integration at moment or for you its not the goal?

**Comment by randyzwitch** [comment]
Hi @archenroot - 

In the future, please feel free to start a different thread (as you have on our Community forum) instead of posting to closed threads.

In general, our philosophy has been one of being a complimentary analytics solution with other open-source technologies. But in the end, we're not necessarily chasing any one technology, as we are our own product offering.

We are already part of the overall RAPIDS eco-system (MapD was one of the founding members of the GPU Open Analytics Initiative), and so any work that's being done there benefits any tool that can work with the GPU data frame provided by cuDF. We already provide the ability to get results of a query as a GPU dataframe, and provide the ability to load data into OmniSci via Arrow. So depending on whatever gets built in Spark, we may or may not be able to accept the output from those processes right out of the box. We'll just have to see when they have something that works.

**Comment by archenroot** [comment]
@randyzwitch - sure, you are right (I am dead threat troll :-) )

Thx for comprehensive answer.

Add -  OmniSci via Arrow - nice i didn't know about this (actually discovering full mapd potential). I think cuDF is the main building block.

Thanks again and lets see what future brings :-)
