### ISSUE TITLE
How to enable backend rendering?

### ISSUE THREAD

**Issue by hijiangtao** [mapd/mapd-core#8]
I am sorry about disturbing your guys here, since I didn't find an appropriate way to contact you about the usage and valuable features in mapd's community version. And I may also raise the issue in a inappropriate sub-repo of mapd...

The thing I want to know is that how to enable backend rendering in mapd? I don't know whether I should open it by setting something specifically, or it's only a valuable feature for enterprise version?

Thanks for your hard work for contributing to this excellent product. :-)

**Comment by m1mc** [comment]
Hi Tao, this is not an issue. Basically, you need `cmake /path/to/mapd-core/build-dir -DENABLE_RENDERING=ON` and use MapD Immerse visual analytics client for non-commercial use. Pls put your question [here](https://community.mapd.com/) in future.

**Comment by hijiangtao** [comment]
OK, thanks very much. Sorry for my silly question again. :-)

**Comment by tmostak** [comment]
We are currently looking at adding infrastructure so that OS users can download the rendering object files as a binary to enable the functionality. Please stay tuned! 

Adding @andrewseidl.

**Comment by hijiangtao** [comment]
@tmostak Thanks for your guys' contributions on that, I will keep an eye on it. Currently, I will try to use community version on this functionality. :-)
