### ISSUE TITLE
If the size of dataset exceeds the amount of device memory ???

### ISSUE THREAD

**Issue by neko940709** [mapd/mapd-core#81]
About this topic, I've seen two options to deal with it: the first is turn off the option "enable_watchdog", the second is turn on the option "allow-cpu-retry". BUT I've read the source code of Mapd Core 3.1.2, the exception occurs at` handleRetry(`) in `RelAlgExecutor.cpp`, where the code is the following:
```
  if (error_code == Executor::ERR_OUT_OF_GPU_MEM) {
    if (g_enable_watchdog && !g_allow_cpu_retry) {
      throw std::runtime_error(getErrorMessageFromCode(error_code));
    }
    const auto ra_exe_unit = decide_approx_count_distinct_implementation(
        work_unit.exe_unit, table_infos, executor_, co.device_type_, target_exprs_owned_);
    result = {executor_->executeWorkUnit(&error_code,
                                         max_groups_buffer_entry_guess,
                                         is_agg,
                                         table_infos,
                                         ra_exe_unit,
                                         co,
                                         eo_no_multifrag,
                                         cat_,
                                         executor_->row_set_mem_owner_,
                                         nullptr,
                                         true),
              targets_meta};
......
```
 From the code I cannot find the difference of these two options. Whether they take the same solution? If not, could you show me where the point code is?

**Comment by neko940709** [comment]
More, I wanna know how the CPU MODE execute on Mapd??

**Comment by asuhan** [comment]
I'm not sure I understand your question. MapD can run *exclusively* on CPUs if you don't have GPUs and that's what we'd recommend anyway if you don't have enough GPU memory.

**Comment by neko940709** [comment]
MapD surely can run on CPU and I've tried it successfully, but I wonder HOW it runs under CPU mode. Other answers said MapD uses BATCHED EXECUTION in CPU. Could you please describe this execution process?

**Comment by asuhan** [comment]
The execution process is not, at a high level, different. We generate native code which runs on the CPU cores, in the host address space as opposed to the device address space (for GPU execution). That being said, I'm sure what "batched execution" is.

**Comment by randyzwitch** [comment]
Closing this issue. If this continues to be an issue with using one of our current 4.x releases, please open a new issue or start a conversation at https://community.mapd.com/
