### ISSUE TITLE
tombstone

### ISSUE THREAD

**Issue by fleapapa** [mapd/mapd-core#87]
I searched through source code of mapd-core and found no word like "tombstone".

It may hint that mapd-core doesn't do any data (file) compaction for now. Is compaction in future milestone?

My point for such tombstone is similar to that in [issue 86](https://github.com/mapd/mapd-core/issues/86). If compaction is supported (thus is DELETE), by augmenting mapdql in similar appraoch, adding UPDATE function to mapd is possible without significant changes to mapd core.

**Comment by asuhan** [comment]
Updates and deletes are definitely on the road-map. And yes, compaction too.
