### ISSUE TITLE
Implement RPC endpoint for loading serialized Arrow record batches

### ISSUE THREAD

**Issue by wesm** [mapd/mapd-core#89]
e.g. `load_table_binary_arrow`. This would yield superior data import performance for clients that are able to create Arrow-formatted data in memory (see discussion in https://github.com/mapd/pymapd/pull/50)

I note that the codebase is accumulating a lot of usages of the `ENABLE_ARROW_CONVERTER` compiler definition. Would there be objections to make this a non-optional dependency? It is simple to build and does not introduce any additional transitive dependencies. We are quite committed to ensuring that the Arrow C++ libraries are a reliable thirdparty component for production applications, so if having this as a dependency in production caused you any problems, we would make fixing them a priority.

**Comment by asuhan** [comment]
I'm fine with making it mandatory. @andrewseidl, we'll have to make sure that all the internal builds keep working.
