### ISSUE TITLE
Does MapD support complicated JOIN operations where more than two tables?

### ISSUE THREAD

**Issue by neko940709** [mapd/mapd-core#96]
In version 3.1.2, I've tried JOIN with three tables and the server crashed finally. I just wonder whether the current version has done this work or not?
My sql is like this:

`select MSISDN,stat_date,AREA_ID,USER_ID from md_per_inf_attribute_day z  join (select S00000000023 from EDC_SUB_TEMP_10000049978_ZZ5 a  left join md_vw_per_user02_day b on b.USER_ID=a.S00000000023 and b.IS_HMD_MDR_MG=1) y  on z.USER_ID=y.S00000000023 where z.AREA_ID in (select t.area_id from edc_area t where t.parent_area_id in (1000515))`

**Comment by asuhan** [comment]
For certain cases, like equi-joins on a star schema, yes. In a few weeks we'll have much better support and performance for joins on arbitrary schemas.

What are the table definitions in your example? I'm going to have a look at your query. It doesn't look like join on more than two tables, is this the result of an attempt to rewrite your desired query? I see there are multiple tables involved, but each join is actually 2-way. We should be able to get this running.

**Comment by dwayneberry** [comment]
Please retry your query with 3.3.1 and share your ddl and some data

**Comment by randyzwitch** [comment]
Closing this issue. If you are still having problems with one of our current 4.x releases, please open an new issue or start a conversation at https://community.mapd.com/
